
TURN = 1
WEEKS = 1

Towns_Types = {"TOWN_HEAVEN","TOWN_PRESERVE","TOWN_INFERNO","TOWN_NECROMANCY","TOWN_ACADEMY","TOWN_DUNGEON","TOWN_FORTRESS","TOWN_STRONGHOLD"}
Dwellings_T1 = {"BUILDING_PEASANT_HUT","BUILDING_FAIRIE_TREE","BUILDING_IMP_CRUCIBLE","BUILDING_GRAVEYARD","BUILDING_WORKSHOP","BUILDING_BATTLE_ACADEMY","BUILDING_FORTRESS_DEFENDERS","BUILDING_STRONGHOLD_GOBLINS"}
Dwellings_T2 = {"BUILDING_ARCHERS_HOUSE","BUILDING_WOOD_GUARD_QUARTERS","BUILDING_DEMON_GATE","BUILDING_FORGOTTEN_CRYPT","BUILDING_STONE_PARAPET","BUILDING_SHADOW_STONE","BUILDING_FORTRESS_AXEMEN","BUILDING_STRONGHOLD_CENTAURS"}
Dwellings_T3 = {"BUILDING_BARRACKS","BUILDING_HIGH_CABINS","BUILDING_KENNELS","BUILDING_RUINED_TOWER","BUILDING_GOLEM_FORGE","BUILDING_MAZE","BUILDING_FORTRESS_BEAR_RIDERS","BUILDING_STRONGHOLD_WARRIORS"}
Dwellings_MP = {"BUILDING_HEAVEN_MILITARY_POST","BUILDING_PRESERVE_MILITARY_POST","BUILDING_INFERNO_MILITARY_POST","BUILDING_NECROPOLIS_MILITARY_POST","BUILDING_ACADEMY_MILITARY_POST","BUILDING_DUNGEON_MILITARY_POST","BUILDING_FORTRESS_MILITARY_POST","BUILDING_STRONGHOLD_MILITARY_POST"}

MAP_TOWNS = {}
PLAYER_MAIN_TOWN = {}

COMBAT_TRIGGERING_OBJECTS = {
    "CREATURE",
    "BUILDING_CRYPT",
    "BUILDING_GARGOYLE_STONEVAULT",
    "BUILDING_DWARVEN_TREASURE",
    "BUILDING_BLOOD_TEMPLE",
    "BUILDING_NAGA_BANK",
    "BUILDING_NAGA_TEMPLE",
    "BUILDING_TREANT_THICKET",
    "BUILDING_UNKEMPT",
    "BUILDING_LEAN_TO",
    "BUILDING_SUNKEN_TEMPLE",
    "BUILDING_PYRAMID",
    "BUILDING_DEMOLISH",
    "BUILDING_BUOY",
    "BUILDING_CYCLOPS_STOCKPILE",
    "BUILDING_ABANDONED_MINE",
    "BUILDING_DRAGON_UTOPIA",
}

RESOURCE_GENERATING_OBJECTS = {
    ["BUILDING_SAWMILL"]        = {type=WOOD, amount=2},
    ["BUILDING_ORE_PIT"]        = {type=ORE, amount=2},
    ["BUILDING_ALCHEMIST_LAB"]  = {type=MERCURY, amount=1},
    ["BUILDING_CRYSTAL_CAVERN"] = {type=CRYSTAL, amount=1},
    ["BUILDING_SULFUR_DUNE"]    = {type=SULFUR, amount=1},
    ["BUILDING_GEM_POND"]       = {type=GEM, amount=1},
    ["BUILDING_GOLD_MINE"]      = {type=GOLD, amount=1000},
    ["BUILDING_ABANDONED_MINE"] = {type=GOLD, amount=500},
    ["BUILDING_DWARVEN_WARREN"] = {type=nil, amount=1},
}


SPIRITISM_SCHOOL_AFFINITY = {
    [H_KARUKAT] = SPELL_SCHOOL_NATURAL,
    [H_HAGGASH] = SPELL_SCHOOL_ANY,
    [H_MUKHA] = SPELL_SCHOOL_DESTRUCT,
    [H_URGHAT] = SPELL_SCHOOL_DARK,
    [H_ZOULEIKA] = SPELL_SCHOOL_LIGHT,
    [H_KUJIN] = SPELL_SCHOOL_ANY,
}


-- log("Loaded advmap-data.lua")
ROUTINES_LOADED[8] = 1
