
TURN = 1
WEEKS = 1

DIFFICULTY = GetDifficulty()

MAP_TOWNS = {}
MAP_TOWN_BUILDINGS = {}
PLAYER_MAIN_TOWN = {}
PLAYER_MAGIC_GUILD_LEVEL = {0,0,0,0,0,0,0,0}
HERO_MAGIC_GUILD_BONUS = {}


Towns_Types = {"TOWN_HEAVEN","TOWN_PRESERVE","TOWN_INFERNO","TOWN_NECROMANCY","TOWN_ACADEMY","TOWN_DUNGEON","TOWN_FORTRESS","TOWN_STRONGHOLD"}
Dwellings_T1 = {"BUILDING_PEASANT_HUT","BUILDING_FAIRIE_TREE","BUILDING_IMP_CRUCIBLE","BUILDING_GRAVEYARD","BUILDING_WORKSHOP","BUILDING_BATTLE_ACADEMY","BUILDING_FORTRESS_DEFENDERS","BUILDING_STRONGHOLD_GOBLINS"}
Dwellings_T2 = {"BUILDING_ARCHERS_HOUSE","BUILDING_WOOD_GUARD_QUARTERS","BUILDING_DEMON_GATE","BUILDING_FORGOTTEN_CRYPT","BUILDING_STONE_PARAPET","BUILDING_SHADOW_STONE","BUILDING_FORTRESS_AXEMEN","BUILDING_STRONGHOLD_CENTAURS"}
Dwellings_T3 = {"BUILDING_BARRACKS","BUILDING_HIGH_CABINS","BUILDING_KENNELS","BUILDING_RUINED_TOWER","BUILDING_GOLEM_FORGE","BUILDING_MAZE","BUILDING_FORTRESS_BEAR_RIDERS","BUILDING_STRONGHOLD_WARRIORS"}
Dwellings_MP = {"BUILDING_HEAVEN_MILITARY_POST","BUILDING_PRESERVE_MILITARY_POST","BUILDING_INFERNO_MILITARY_POST","BUILDING_NECROPOLIS_MILITARY_POST","BUILDING_ACADEMY_MILITARY_POST","BUILDING_DUNGEON_MILITARY_POST","BUILDING_FORTRESS_MILITARY_POST","BUILDING_STRONGHOLD_MILITARY_POST"}


COMBAT_TRIGGERING_OBJECTS = {
    "CREATURE",
    "BUILDING_CRYPT",
    "BUILDING_GARGOYLE_STONEVAULT",
    "BUILDING_DWARVEN_TREASURE",
    "BUILDING_BLOOD_TEMPLE",
    "BUILDING_NAGA_BANK",
    "BUILDING_NAGA_TEMPLE",
    "BUILDING_TREANT_THICKET",
    "BUILDING_UNKEMPT",
    "BUILDING_LEAN_TO",
    "BUILDING_SUNKEN_TEMPLE",
    "BUILDING_PYRAMID",
    "BUILDING_DEMOLISH",
    "BUILDING_BUOY",
    "BUILDING_CYCLOPS_STOCKPILE",
    "BUILDING_ABANDONED_MINE",
    "BUILDING_DRAGON_UTOPIA",
}

RESOURCE_GENERATING_OBJECTS = {
    ["BUILDING_SAWMILL"]        = {type=WOOD, amount=2},
    ["BUILDING_ORE_PIT"]        = {type=ORE, amount=2},
    ["BUILDING_ALCHEMIST_LAB"]  = {type=MERCURY, amount=1},
    ["BUILDING_CRYSTAL_CAVERN"] = {type=CRYSTAL, amount=1},
    ["BUILDING_SULFUR_DUNE"]    = {type=SULFUR, amount=1},
    ["BUILDING_GEM_POND"]       = {type=GEM, amount=1},
    ["BUILDING_GOLD_MINE"]      = {type=GOLD, amount=1000},
    ["BUILDING_ABANDONED_MINE"] = {type=GOLD, amount=500},
    ["BUILDING_DWARVEN_WARREN"] = {type=nil, amount=1},
}

FASTTRAVEL_GATE_OBJECTS = {
    "BUILDING_SUBTERRA_GATE",
    "BUILDING_MONOLITH_ONE_WAY_ENTRANCE",
    "BUILDING_MONOLITH_ONE_WAY_EXIT",
    "BUILDING_MONOLITH_TWO_WAY",
}

MAP_GATES = {}


SPIRITISM_SCHOOL_AFFINITY = {
    [H_KARUKAT] = SPELL_SCHOOL_NATURAL,
    [H_HAGGASH] = SPELL_SCHOOL_ANY,
    [H_MUKHA] = SPELL_SCHOOL_DESTRUCT,
    [H_URGHAT] = SPELL_SCHOOL_DARK,
    [H_ZOULEIKA] = SPELL_SCHOOL_LIGHT,
    [H_KUJIN] = SPELL_SCHOOL_ANY,
}

ONGOING_BATTLES = {}
WON_BATTLES = {}
LAST_BATTLES = {}

FACTION_RESOURCE = { [HAVEN]=CRYSTAL, [PRESERVE]=GEM, [FORTRESS]=CRYSTAL, [ACADEMY]=GEM, [DUNGEON]=SULFUR, [NECROPOLIS]=MERCURY, [INFERNO]=SULFUR, [STRONGHOLD]=MERCURY }
FACTION_TOWN_BUILDINGS = {
    [HAVEN]={[TOWN_BUILDING_HAVEN_TRAINING_GROUNDS]=0,[TOWN_BUILDING_HAVEN_MONUMENT_TO_FALLEN_HEROES]=0,[TOWN_BUILDING_HAVEN_WOLF_KENNEL]=0,[TOWN_BUILDING_HAVEN_STABLE]=0,[TOWN_BUILDING_HAVEN_FARMS]=0},
    [PRESERVE]={[TOWN_BUILDING_PRESERVE_AVENGERS_BROTHERHOOD]=0,[TOWN_BUILDING_PRESERVE_SPARKLING_FONTAINS]=0,[TOWN_BUILDING_PRESERVE_BLOOMING_GROVE]=0,[TOWN_BUILDING_PRESERVE_TREANT_SAMPLING]=0,[TOWN_BUILDING_PRESERVE_WATCH_TOWER]=0},
    [FORTRESS]={[TOWN_BUILDING_FORTRESS_RUNIC_SHRINE]=0,[TOWN_BUILDING_FORTRESS_ARENA]=0,[TOWN_BUILDING_FORTRESS_GUARDPOST]=0,[TOWN_BUILDING_FORTRESS_RUNIC_STONEWORKS]=0,[TOWN_BUILDING_FORTRESS_RUNIC_ACADEMY]=0},
    [ACADEMY]={[TOWN_BUILDING_ACADEMY_LIBRARY]=0,[TOWN_BUILDING_ACADEMY_ARCANE_FORGE]=0,[TOWN_BUILDING_ACADEMY_ARTIFACT_MERCHANT]=0,[TOWN_BUILDING_ACADEMY_TREASURE_CAVE]=0,[TOWN_BUILDING_ACADEMY_ALCHEMY_LAB]=0},
    [DUNGEON]={[TOWN_BUILDING_DUNGEON_ALTAR_OF_ELEMENTS]=0,[TOWN_BUILDING_DUNGEON_RITUAL_PIT]=0,[TOWN_BUILDING_DUNGEON_TRADE_GUILD]=0,[TOWN_BUILDING_DUNGEON_HALL_OF_INTRIGUE]=0},
    [NECROPOLIS]={[TOWN_BUILDING_NECROMANCY_AMPLIFIER]=0,[TOWN_BUILDING_NECROMANCY_UNHOLY_TEMPLE]=0,[TOWN_BUILDING_NECROMANCY_UNEARHED_GRAVES]=0,[TOWN_BUILDING_NECROMANCY_DRAGON_TOMBSTONE]=0},
    [INFERNO]={[TOWN_BUILDING_INFERNO_INFERNAL_LOOM]=0,[TOWN_BUILDING_INFERNO_BRIMSTONE_CLOUDS]=0,[TOWN_BUILDING_INFERNO_ETERNAL_SUFFERING]=0,[TOWN_BUILDING_INFERNO_HALLS_OF_HORROR]=0,[TOWN_BUILDING_INFERNO_SACRIFICIAL_PIT]=0},
    [STRONGHOLD]={[TOWN_BUILDING_STRONGHOLD_HALL_OF_TRIAL]=0,[TOWN_BUILDING_STRONGHOLD_GARBAGE_PILE]=0,[TOWN_BUILDING_STRONGHOLD_TRAVELLERS_SHELTER]=0,[TOWN_BUILDING_STRONGHOLD_PILE_OF_OUR_FOES]=0,[TOWN_BUILDING_STRONGHOLD_SLAVE_MARKET]=0}
}

DAILY_RESOURCES = {
    [1] = { [0]=0,[1]=0,[2]=0,[3]=0,[4]=0,[5]=0,[6]=0 },
    [2] = { [0]=0,[1]=0,[2]=0,[3]=0,[4]=0,[5]=0,[6]=0 },
    [3] = { [0]=0,[1]=0,[2]=0,[3]=0,[4]=0,[5]=0,[6]=0 },
    [4] = { [0]=0,[1]=0,[2]=0,[3]=0,[4]=0,[5]=0,[6]=0 },
    [5] = { [0]=0,[1]=0,[2]=0,[3]=0,[4]=0,[5]=0,[6]=0 },
    [6] = { [0]=0,[1]=0,[2]=0,[3]=0,[4]=0,[5]=0,[6]=0 },
    [7] = { [0]=0,[1]=0,[2]=0,[3]=0,[4]=0,[5]=0,[6]=0 },
    [8] = { [0]=0,[1]=0,[2]=0,[3]=0,[4]=0,[5]=0,[6]=0 },
}


log.trace("Loaded advmap-data.lua")
