
name: Package folder
description: Create a .pak file from a repository directory

inputs:
  folder:
    description: Folder to pak
    type: string
    required: true

runs:
  using: composite
  steps:
    - name: Make .pak
      run: zip -q -r h5x-{{ inputs.folder }}.pak *
      shell: bash
      working-directory: game_data/{{ inputs.folder }}
    - name: Upload .pak
      uses: actions/upload-artifact@v4
      with:
        name: h5x-{{ inputs.folder }}
        path: game_data/{{ inputs.folder }}/h5x-{{ inputs.folder }}.pak