
TURN = 1

PLAYER_BRAIN = {
	[1] = OBSERVER,
	[2] = OBSERVER,
	[3] = OBSERVER,
	[4] = OBSERVER,
	[5] = OBSERVER,
	[6] = OBSERVER,
	[7] = OBSERVER,
	[8] = OBSERVER,
}

PLAYER_MAIN_TOWN = {}


SPIRITISM_SCHOOL_AFFINITY = {
    [H_SHAKKARUKAT] = SPELL_SCHOOL_ANY,
    [H_KUJIN] = SPELL_SCHOOL_ANY,
    [H_SHIVA] = SPELL_SCHOOL_ANY,
    [H_MUKHA] = SPELL_SCHOOL_ANY,
    [H_HAGGASH] = SPELL_SCHOOL_ANY,
    [H_URGHAT] = SPELL_SCHOOL_ANY,
    [H_GARUNA] = SPELL_SCHOOL_ANY,
    [H_ZOULEIKA] = SPELL_SCHOOL_ANY,
    [H_ERIKA] = SPELL_SCHOOL_ANY,
}


SOURCE_LOADED["advmap-data"] = 1