--
-- Resources
--

RESOURCE_TEXT = {
    [0] = "Wood",
    [1] = "Ore",
    [2] = "Mercury",
    [3] = "Cystal",
    [4] = "Sulfur",
    [5] = "Gem",
    [6] = "Gold",
}

RESOURCE_NAME_FILE = {
    [0] = "/Text/Game/Scripts/Resources/Wood.txt",
    [1] = "/Text/Game/Scripts/Resources/Ore.txt",
    [2] = "/Text/Game/Scripts/Resources/Mercury.txt",
    [3] = "/Text/Game/Scripts/Resources/Crystal.txt",
    [4] = "/Text/Game/Scripts/Resources/Sulfur.txt",
    [5] = "/Text/Game/Scripts/Resources/Gem.txt",
    [6] = "/Text/Game/Scripts/Resources/Gold.txt",
}


--
-- Attributes
--

ATTRIBUTE_TEXT = {
    [0] = "Experience",
    [1] = "Attack",
    [2] = "Defense",
    [3] = "Spellpower",
    [4] = "Knowledge",
    [5] = "Luck",
    [6] = "Morale",
    [7] = "Movement",
    [8] = "Mana",
}

ATTRIBUTE_NAME_FILE = {
    [1] = "/GameMechanics/RefTables/HeroAttribute/Offence.txt",
    [2] = "/GameMechanics/RefTables/HeroAttribute/Defence.txt",
    [3] = "/GameMechanics/RefTables/HeroAttribute/SpellPower.txt",
    [4] = "/GameMechanics/RefTables/HeroAttribute/Knowledge.txt",
}


--
-- Factions
--

FACTION_TEXT = {
    [0] = "Neutral",
    [1] = "Haven",
    [2] = "Preserve",
    [3] = "Inferno",
    [4] = "Necro",
    [5] = "Academy",
    [6] = "Dungeon",
    [7] = "Fortress",
    [8] = "Stronghold",
}


--
-- War machines
--

WAR_MACHINE_NAME_FILE = {
    [1] = "/Text/Game/Creatures/WarMachines/Ballista.txt",
    [2] = "/Text/Game/Creatures/WarMachines/Catapult.txt",
    [3] = "/Text/Game/Creatures/WarMachines/FirstAidTent.txt",
    [4] = "/Text/Game/Creatures/WarMachines/AmmoCart.txt",
}


--
-- Artifacts
--

ARTIFACT_NAME_FILE = {
    [ARTIFACT_SWORD_OF_MIGHT]                = "/Text/Game/Artifacts/SwordOfMight/Name.txt",
    [ARTIFACT_AXE_OF_THE_MOUNTAIN_LORDS]     = "/Text/Game/Artifacts/AxeOfTheMountainLords/Name.txt",
    [ARTIFACT_WAND_OF_SPELL]                 = "/Text/Game/Artifacts/WandOfSpell/Name.txt",
    [ARTIFACT_UNICORN_HORN_BOW]              = "/Text/Game/Artifacts/UnicornHornBow/Name.txt",
    [ARTIFACT_TITANS_TRIDENT]                = "/Text/Game/Artifacts/TitansTrident/Name.txt",
    [ARTIFACT_STAFF_OF_THE_NETHERWORLD]      = "/Text/Game/Artifacts/StaffOfTheNetherworld/Name.txt",
    [ARTIFACT_NO_RETREAT]                    = "/Text/Game/Artifacts/NoRetreat/Name.txt",
    [ARTIFACT_FOUR_LEAF_CLOVER]              = "/Text/Game/Artifacts/FourLeafClover/Name.txt",
    [ARTIFACT_SHIELD_OF_CRYSTAL_ICE]         = "/Text/Game/Artifacts/ShieldOfCrystalIce/Name.txt",
    [ARTIFACT_OCEAN_CHARM]                   = "/Text/Game/Artifacts/OceanCharm/Name.txt",
    [ARTIFACT_CROWN_OF_COURAGE]              = "/Text/Game/Artifacts/CrownOfCourage/Name.txt",
    [ARTIFACT_ALL_SEEING_CROWN]              = "/Text/Game/Artifacts/AllSeeingCrown/Name.txt",
    [ARTIFACT_SENTINELS_BREASTPLATE]         = "/Text/Game/Artifacts/SentinelsBreastplate/Name.txt",
    [ARTIFACT_BREASTPLATE_OF_ELDRICHT_MIGHT] = "/Text/Game/Artifacts/BreastplateOfEldrichtMight/Name.txt",
    [ARTIFACT_PENDANT_OF_MASTERY]            = "/Text/Game/Artifacts/PedantOfMastery/Name.txt",
    [ARTIFACT_NECKLACE_OF_THE_EAGLE]         = "/Text/Game/Artifacts/NecklaceOfTheEagle/Name.txt",
    [ARTIFACT_WAR_DRUMS]                     = "/Text/Game/Artifacts/WarDrums/Name.txt",
    [ARTIFACT_EVERCOLD_ICICLE]               = "/Text/Game/Artifacts/EvercoldIcicle/Name.txt",
    [ARTIFACT_NECKLACE_OF_VICTORY]           = "/Text/Game/Artifacts/NecklaceOfVictory/Name.txt",
    [ARTIFACT_MAGNETIC_RING]                 = "/Text/Game/Artifacts/MagneticRing/Name.txt",
    [ARTIFACT_WAR_BANNER]                    = "/Text/Game/Artifacts/WarBanner/Name.txt",
    [ARTIFACT_CELESTIAL_JUSTICAR_SWORD]      = "/Text/Game/Artifacts/CelestialJusticarSword/Name.txt",
    [ARTIFACT_RING_OF_THE_BROKEN_WILL]       = "/Text/Game/Artifacts/RingOfTheBrokenWill/Name.txt",
    [ARTIFACT_BOOTS_OF_THE_SWIFT_JOURNEY]    = "/Text/Game/Artifacts/BootsOfTheSwiftJounrey/Name.txt",
    [ARTIFACT_GOLDEN_HORSESHOE]              = "/Text/Game/Artifacts/GoldenHorseshoe/Name.txt",
    [ARTIFACT_BOOTS_OF_THE_OPEN_ROAD]        = "/Text/Game/Artifacts/BootsOfTheOpenRoad/Name.txt",
    [ARTIFACT_BOOTS_OF_INTERFERENCE]         = "/Text/Game/Artifacts/BootsOfInterference/Name.txt",
    [ARTIFACT_ENDLESS_SACK_OF_GOLD]          = "/Text/Game/Artifacts/EndlessSackOfGold/Name.txt",
    [ARTIFACT_ENDLESS_POUCH_OF_GOLD]         = "/Text/Game/Artifacts/EndlessPouchOfGold/Name.txt",
    [ARTIFACT_ANGEL_WINGS]                   = "/Text/Game/Artifacts/AngelWings/Name.txt",
    [ARTIFACT_CAPE_OF_KINGS]                 = "/Text/Game/Artifacts/CapeOfKings/Name.txt",
    [ARTIFACT_SOLAR_RING]                    = "/Text/Game/Artifacts/SolarRing/Name.txt",
    [ARTIFACT_CLOAK_OF_DEATHS_SHADOW]        = "/Text/Game/Artifacts/CloakOfDeathsShadow/Name.txt",
    [ARTIFACT_TURBAN_OF_ENLIGHTMENT]         = "/Text/Game/Artifacts/TurbanOfEnlightment/Name.txt",
    [ARTIFACT_SCALE_MAIL_OF_ENLIGHTMENT]     = "/Text/Game/Artifacts/ScaleMailOfEnlightment/Name.txt",
    [ARTIFACT_DRAGON_SCALE_ARMOR]            = "/Text/Game/Artifacts/DragonScaleArmor/Name.txt",
    [ARTIFACT_DRAGON_SCALE_SHIELD]           = "/Text/Game/Artifacts/DragonScaleShield/Name.txt",
    [ARTIFACT_DRAGON_BONE_GRAVES]            = "/Text/Game/Artifacts/DragonBoneGraves/Name.txt",
    [ARTIFACT_DRAGON_WING_MANTLE]            = "/Text/Game/Artifacts/DragonWingMantle/Name.txt",
    [ARTIFACT_DRAGON_TEETH_NECKLACE]         = "/Text/Game/Artifacts/DragonTeethNecklace/Name.txt",
    [ARTIFACT_DRAGON_TALON_CROWN]            = "/Text/Game/Artifacts/DragonTalonCrown/Name.txt",
    [ARTIFACT_DRAGON_EYE_RING]               = "/Text/Game/Artifacts/DragonEyeRing/Name.txt",
    [ARTIFACT_DRAGON_FLAME_TONGUE]           = "/Text/Game/Artifacts/DragonFlameTongue/Name.txt",
    [ARTIFACT_ROBE_OF_THE_MAGISTER]          = "/Text/Game/Artifacts/RobeOfTheMagister/Name.txt",
    [ARTIFACT_STAFF_OF_THE_MAGISTER]         = "/Text/Game/Artifacts/StaffOfTheMagister/Name.txt",
    [ARTIFACT_CROWN_OF_THE_MAGISTER]         = "/Text/Game/Artifacts/CrownOfTheMagister/Name.txt",
    [ARTIFACT_RING_OF_THE_MAGISTER]          = "/Text/Game/Artifacts/RingOfTheMagister/Name.txt",
    [ARTIFACT_SHANTIRI_MOON_DISC]            = "/Text/Game/Artifacts/ShantiriMoonDisc/Name.txt",
    [ARTIFACT_PLUMED_BOOTS]                  = "/Text/Game/Artifacts/PlumedBoots/Name.txt",
    [ARTIFACT_CELESTIAL_JUSTICAR_HELMET]     = "/Text/Game/Artifacts/CelestialJusticarHelmet/Name.txt",
    [ARTIFACT_HELM_OF_THE_DWARVEN_KINGS]     = "/Text/Game/Artifacts/HelmOfTheDwarvenKings/Name.txt",
    [ARTIFACT_MAGIC_SCROLL_OF_SPELL]         = "/Text/Game/Artifacts/MagicScrollOfSpell/Name.txt",
    [ARTIFACT_BOOTS_OF_LEVITATION]           = "/Text/Game/Artifacts/BootsOfLevitation/Name.txt",
    [ARTIFACT_HELM_OF_THE_LICH]              = "/Text/Game/Artifacts/HelmOfTheLich/Name.txt",
    [ARTIFACT_ARMOR_OF_VALOR]                = "/Text/Game/Artifacts/ArmorOfValor/Name.txt",
    [ARTIFACT_BOOTS_OF_SWIFTNESS]            = "/Text/Game/Artifacts/BootsOfSwiftness/Name.txt",
    [ARTIFACT_MOONBLADE]                     = "/Text/Game/Artifacts/Moonblade/Name.txt",
    [ARTIFACT_WAR_HORN]                      = "/Text/Game/Artifacts/WarHorn/Name.txt",
    [ARTIFACT_BAND_OF_CONJURER]              = "/Text/Game/Artifacts/BandOfConjurer/Name.txt",
    [ARTIFACT_EMERALD_SLIPPERS]              = "/Text/Game/Artifacts/EmeraldSlippers/Name.txt",
    [ARTIFACT_CLOAK_OF_SYLANNA]              = "/Text/Game/Artifacts/CloakOfSylanna/Name.txt",
    [ARTIFACT_CURSED_RING]                   = "/Text/Game/Artifacts/CursedRing/Name.txt",
    [ARTIFACT_TUNIC_OF_CARVED_FLESH]         = "/Text/Game/Artifacts/TunicOfCarvedFlesh/Name.txt",
    [ARTIFACT_RING_OF_CAUTION]               = "/Text/Game/Artifacts/RingOfCaution/Name.txt",
    [ARTIFACT_HELM_OF_CHAOS]                 = "/Text/Game/Artifacts/HelmOfChaos/Name.txt",
    [ARTIFACT_PENDANT_OF_CONFLUX]            = "/Text/Game/Artifacts/PendantOfConflux/Name.txt",
    [ARTIFACT_SANDALS_OF_THE_BLESSED]        = "/Text/Game/Artifacts/SandalsOfTheBlessed/Name.txt",
    [ARTIFACT_SANDROS_CLOAK]                 = "/Text/Game/Artifacts/SandrosCloak/Name.txt",
    [ARTIFACT_RING_OF_THE_UNREPENTANT]       = "/Text/Game/Artifacts/RingOfTheUnrepentant/Name.txt",
    [ARTIFACT_AMULET_OF_NECROMANCY]          = "/Text/Game/Artifacts/AmuletOfNecromancy/Name.txt",
    [ARTIFACT_RING_OF_THE_SHADOWBRAND]       = "/Text/Game/Artifacts/RingOfTheShadowbrand/Name.txt",
    [ARTIFACT_CUIRASS_OF_THE_DWARVEN_KINGS]  = "/Text/Game/Artifacts/CuirassOfTheDwarvenKings/Name.txt",
    [ARTIFACT_GREAVES_OF_THE_DWARVEN_KINGS]  = "/Text/Game/Artifacts/GreavesOfTheDwarvenKings/Name.txt",
    [ARTIFACT_TOME_OF_DESTRUCTION]           = "/Text/Game/Artifacts/TomeOfDestruction/Name.txt",
    [ARTIFACT_TOME_OF_LIGHT]                 = "/Text/Game/Artifacts/TomeOfLight/Name.txt",
    [ARTIFACT_TOME_OF_DARKNESS]              = "/Text/Game/Artifacts/TomeOfDarkness/Name.txt",
    [ARTIFACT_TOME_OF_NATURE]                = "/Text/Game/Artifacts/TomeOfNature/Name.txt",
    [ARTIFACT_BEGINNER_MAGIC_STICK]          = "/Text/Game/Artifacts/BeginnerMagicStick/Name.txt",
    [ARTIFACT_RUNIC_WAR_AXE]                 = "/Text/Game/Artifacts/RunicWarAxe/Name.txt",
    [ARTIFACT_RUNIC_WAR_HARNESS]             = "/Text/Game/Artifacts/RunicWarHarness/Name.txt",
    [ARTIFACT_SKULL_OF_THE_FORBIDDEN]        = "/Text/Game/Artifacts/SkullOfTheForbidden/Name.txt",
    [ARTIFACT_FROZEN_HEART]                  = "/Text/Game/Artifacts/FrozenHeart/Name.txt",
    [ARTIFACT_PHOENIX_FEATHER_CAPE]          = "/Text/Game/Artifacts/PhoenixFeatherCape/Name.txt",
    [ARTIFACT_RUNE_OF_FLAME]                 = "/Text/Game/Artifacts/RuneOfFlame/Name.txt",
    [ARTIFACT_TAROT_DECK]                    = "/Text/Game/Artifacts/TarotDeck/Name.txt",
    [ARTIFACT_CROWN_OF_LEADER]               = "/Text/Game/Artifacts/CrownOfLeader/Name.txt",
    [ARTIFACT_MASK_OF_EQUITY]                = "/Text/Game/Artifacts/MaskOfEquity/Name.txt",
    [ARTIFACT_EDGE_OF_BALANCE]               = "/Text/Game/Artifacts/EdgeOfBalance/Name.txt",
    [ARTIFACT_RING_OF_MACHINE_AFFINITY]      = "/Text/Game/Artifacts/RingOfMachineAffinity/Name.txt",
    [ARTIFACT_HORN_OF_PLENTY]                = "/Text/Game/Artifacts/HornOfPlenty/Name.txt",
    [ARTIFACT_RING_OF_BANISHMENT]            = "/Text/Game/Artifacts/RingOfBanishment/Name.txt",
    [ARTIFACT_BOOK_OF_POWER]                 = "/Text/Game/Artifacts/BookOfPower/Name.txt",
    [ARTIFACT_TREEBORN_QUIVER]               = "/Text/Game/Artifacts/TreebornQuiver/Name.txt",
    [ARTIFACT_SACRED_SEED]                   = "/Text/Game/Artifacts/SacredSeed/Name.txt",
    [ARTIFACT_FORTUNE_PICKAXE]               = "/Text/Game/Artifacts/FortunePickaxe/Name.txt",
    [ARTIFACT_CURSED_DICES]                  = "/Text/Game/Artifacts/CursedDices/Name.txt",
    [ARTIFACT_REGAL_ARMOUR]                  = "/Text/Game/Artifacts/RegalArmour/Name.txt",
    [ARTIFACT_CROWN_OF_THE_FROST_LORD]       = "/Text/Game/Artifacts/CrownOfTheFrostLord/Name.txt",
    [ARTIFACT_ALTAR_OF_ELEMENTS_SHARD]       = "/Text/Game/Artifacts/AltarOfElementsShard/Name.txt",
    [ARTIFACT_ELDENAS_RED_SCARF]             = "/Text/Game/Artifacts/EldenasRedScarf/Name.txt",
    [ARTIFACT_ELDENAS_CIRCLET]               = "/Text/Game/Artifacts/EldenasCirclet/Name.txt",
    [ARTIFACT_NAGA_COMMANDERS_HELMET]        = "/Text/Game/Artifacts/NagaCommandersHelmet/Name.txt",
    [ARTIFACT_NECKLACE_OF_THE_BLOODY_CLAW]   = "/Text/Game/Artifacts/NecklaceOfTheBloodyClaw/Name.txt",
    [ARTIFACT_RING_OF_CELERITY]              = "/Text/Game/Artifacts/RingOfCelerity/Name.txt",
    [ARTIFACT_ELDENAS_RED_COAT]              = "/Text/Game/Artifacts/EldenasRedCoat/Name.txt",
    [ARTIFACT_RING_OF_HEALTH]                = "/Text/Game/Artifacts/RingOfLife/Name.txt",
    [ARTIFACT_STEADFAST_SHIELD]              = "/Text/Game/Artifacts/SteadfastShield/Name.txt",
    [ARTIFACT_VIKING_SHIELD]                 = "/Text/Game/Artifacts/VikingShield/Name.txt",
    [ARTIFACT_FORTUNE_BAND_OF_THE_SAINT]     = "/Text/Game/Artifacts/FortuneBandOfTheSaint/Name.txt",
    [ARTIFACT_SENTINELS_BRACER]              = "/Text/Game/Artifacts/SentinelsBracer/Name.txt",
    [ARTIFACT_ANKH_OF_THE_SAINT]             = "/Text/Game/Artifacts/AnkhOfTheSaint/Name.txt",
    [ARTIFACT_CLOAK_OF_THE_SAINT]            = "/Text/Game/Artifacts/CloakOfTheSaint/Name.txt",
    [ARTIFACT_GENJIS_HAT]                    = "/Text/Game/Artifacts/GenjisHat/Name.txt",
    [ARTIFACT_GENJIS_VEST]                   = "/Text/Game/Artifacts/GenjisVest/Name.txt",
    [ARTIFACT_GENJIS_SANDALS]                = "/Text/Game/Artifacts/GenjisSandals/Name.txt",
    [ARTIFACT_GENJIS_SILKSWORD]              = "/Text/Game/Artifacts/GenjisSilksword/Name.txt",
    [ARTIFACT_SENTINELS_HELM]                = "/Text/Game/Artifacts/SentinelsHelm/Name.txt",
    [ARTIFACT_SENTINELS_BOOTS]               = "/Text/Game/Artifacts/SentinelsBoots/Name.txt",
    [ARTIFACT_SENTINELS_SHIELD]              = "/Text/Game/Artifacts/SentinelsShield/Name.txt",
    [ARTIFACT_OBSIDIAN_ARMOR]                = "/Text/Game/Artifacts/ObsidianArmor/Name.txt",
    [ARTIFACT_ELRATHS_DIVINE_SHIELD]         = "/Text/Game/Artifacts/ElrathsDivineShield/Name.txt",
    [ARTIFACT_ROD_OF_TORMENT]                = "/Text/Game/Artifacts/RodOfTorment/Name.txt",
    [ARTIFACT_CODEX_OF_THE_SAINT]            = "/Text/Game/Artifacts/CodexOfTheSaint/Name.txt",
    [ARTIFACT_VIZIRS_CAP]                    = "/Text/Game/Artifacts/VizirsCap/Name.txt",
    [ARTIFACT_PLUNDERER_VEST]                = "/Text/Game/Artifacts/PlundererVest/Name.txt",
    [ARTIFACT_AVENGER_BOW]                   = "/Text/Game/Artifacts/AvengerBow/Name.txt",
    [ARTIFACT_CAPTAINS_HOOK]                 = "/Text/Game/Artifacts/CaptainsHook/Name.txt",
    [ARTIFACT_PLUNDERER_SHOES]               = "/Text/Game/Artifacts/PlundererShoes/Name.txt",
    [ARTIFACT_BUTCHER_GLAIVE]                = "/Text/Game/Artifacts/ButcherGlaive/Name.txt",
    [ARTIFACT_CELESTIAL_JUSTICAR_SHIELD]     = "/Text/Game/Artifacts/CelestialJusticarShield/Name.txt",
    [ARTIFACT_STAFF_OF_THE_SAINT]            = "/Text/Game/Artifacts/StaffOfTheSaint/Name.txt",
    [ARTIFACT_BACKPACK_OF_THE_OPEN_ROAD]     = "/Text/Game/Artifacts/BackpackOfTheOpenRoad/Name.txt",
    [ARTIFACT_MAGMA_SHIELD]                  = "/Text/Game/Artifacts/MagmaShield/Name.txt",
    [ARTIFACT_SYLVAN_AMULET]                 = "/Text/Game/Artifacts/SylvanAmulet/Name.txt",
    [ARTIFACT_SHADOW_MASK]                   = "/Text/Game/Artifacts/ShadowMask/Name.txt",
    [ARTIFACT_BARBARIAN_HELMET]              = "/Text/Game/Artifacts/BarbarianHelmet/Name.txt",
    [ARTIFACT_SKULL_MASK]                    = "/Text/Game/Artifacts/SkullMask/Name.txt",
    [ARTIFACT_SENTINELS_BLADE]               = "/Text/Game/Artifacts/SentinelsBlade/Name.txt",
    [ARTIFACT_VIZIRS_SCIMITAR]               = "/Text/Game/Artifacts/VizirsScimitar/Name.txt",
    [ARTIFACT_BARBARIAN_CAPE]                = "/Text/Game/Artifacts/BarbarianCape/Name.txt",
    [ARTIFACT_SHADOW_BLADE]                  = "/Text/Game/Artifacts/ShadowBlade/Name.txt",
    [ARTIFACT_SHADOWSTEP_SHOES]              = "/Text/Game/Artifacts/ShadowstepShoes/Name.txt",
    [ARTIFACT_RANGERS_CUIRASS]               = "/Text/Game/Artifacts/RangersCuirass/Name.txt",
    [ARTIFACT_MAGISTERS_SANDALS]             = "/Text/Game/Artifacts/MagistersSandals/Name.txt",
    [ARTIFACT_BLAZING_SPELLBOOK]             = "/Text/Game/Artifacts/BlazingSpellbook/Name.txt",
    [ARTIFACT_COLLAR_OF_PRIMAL_RAGE]         = "/Text/Game/Artifacts/CollarOfPrimalRage/Name.txt",
    [ARTIFACT_CENTAUR_CROSSBOW]              = "/Text/Game/Artifacts/CentaurCrossbow/Name.txt",
    [ARTIFACT_DEADWOOD_STAFF]                = "/Text/Game/Artifacts/DeadwoodStaff/Name.txt",
    [ARTIFACT_DEATH_KNIGHT_BOOTS]            = "/Text/Game/Artifacts/DeathKnightBoots/Name.txt",
    [ARTIFACT_BARBARIAN_CUIRASS]             = "/Text/Game/Artifacts/BarbarianCuirass/Name.txt",
    [ARTIFACT_HARPY_BOOTS]                   = "/Text/Game/Artifacts/HarpyBoots/Name.txt",
    [ARTIFACT_PALACE_SHOES]                  = "/Text/Game/Artifacts/PalaceShoes/Name.txt",
    [ARTIFACT_SHACKLES_OF_THE_LAST_MAN]      = "/Text/Game/Artifacts/ShacklesOfTheLastMan/Name.txt",
    [ARTIFACT_LEGENDARY_BOOTS]               = "/Text/Game/Artifacts/LegendaryBoots/Name.txt",
    [ARTIFACT_GOLDEN_GOOSE]                  = "/Text/Game/Artifacts/GoldenGoose/Name.txt",
    [ARTIFACT_DAWN_GLEAM]                    = "/Text/Game/Artifacts/DawnGleam/Name.txt",
    [ARTIFACT_ARDENT_SMITH]                  = "/Text/Game/Artifacts/ArdentSmith/Name.txt",
    [ARTIFACT_CLOAK_OF_DARKNESS]             = "/Text/Game/Artifacts/CloakOfDarkness/Name.txt",
    [ARTIFACT_SHANTIRI_BREASTPLATE]          = "/Text/Game/Artifacts/ShantiriBreastplate/Name.txt",
    [ARTIFACT_SHIELD_OF_THE_WOLF]            = "/Text/Game/Artifacts/ShieldOfTheWolf/Name.txt",
    [ARTIFACT_HELM_OF_THE_WARMAGE]           = "/Text/Game/Artifacts/HelmOfTheWarmage/Name.txt",
    [ARTIFACT_RING_OF_DEVASTATION]           = "/Text/Game/Artifacts/RingOfDevastation/Name.txt",
    [ARTIFACT_RING_OF_STRENGTH]              = "/Text/Game/Artifacts/RingOfStrength/Name.txt",
    [ARTIFACT_SPEAR_OF_THE_FROST_LORD]       = "/Text/Game/Artifacts/SpearOfTheFrostLord/Name.txt",
    [ARTIFACT_STAFF_OF_THE_LYRE]             = "/Text/Game/Artifacts/StaffOfTheLyre/Name.txt",
    [ARTIFACT_SANCTUARYS_CROWN]              = "/Text/Game/Artifacts/SanctuarysCrown/Name.txt",
    [ARTIFACT_PENDANT_OF_THE_LYRE]           = "/Text/Game/Artifacts/PendantOfTheLyre/Name.txt",
    [ARTIFACT_ANCIENT_PROTECTION_CHARM]      = "/Text/Game/Artifacts/AncientProtectionCharm/Name.txt",
    [ARTIFACT_SPIRIT_OF_OPPRESSION]          = "/Text/Game/Artifacts/SpiritOfOppression/Name.txt",
    [ARTIFACT_CRIMSON_SCYTHE]                = "/Text/Game/Artifacts/CrimsonScythe/Name.txt",
    [ARTIFACT_PIRATE_SMASHER]                = "/Text/Game/Artifacts/PirateSmasher/Name.txt",
    [ARTIFACT_ELRATHS_UNITY]                 = "/Text/Game/Artifacts/ElrathsUnity/Name.txt",
    [ARTIFACT_WILL_OF_URGASH]                = "/Text/Game/Artifacts/WillOfUrgash/Name.txt",
    [ARTIFACT_MOONLIGHT_BAND]                = "/Text/Game/Artifacts/MoonlightBand/Name.txt",
    [ARTIFACT_DWARVEN_SMITHY_HAMMER]         = "/Text/Game/Artifacts/DwarvenSmithyHammer/Name.txt",
    [ARTIFACT_RANGERS_CAPE]                  = "/Text/Game/Artifacts/RangersCape/Name.txt",
    [ARTIFACT_MOON_CHARM]                    = "/Text/Game/Artifacts/MoonCharm/Name.txt",
    [ARTIFACT_FORGOTTEN_RING]                = "/Text/Game/Artifacts/ForgottenRing/Name.txt",
    [ARTIFACT_BEARHIDE_WRAPS]                = "/Text/Game/Artifacts/BearhideWraps/Name.txt",
    [ARTIFACT_MOONLIGHT_COAT]                = "/Text/Game/Artifacts/MoonlightCoat/Name.txt",
    [ARTIFACT_DRAGONSBANE]                   = "/Text/Game/Artifacts/Dragonsbane/Name.txt",
    [ARTIFACT_CUIRASS_OF_THE_STAG]           = "/Text/Game/Artifacts/CuirassOfTheStag/Name.txt",
    [ARTIFACT_WRAPS_OF_THE_OWL]              = "/Text/Game/Artifacts/WrapsOfTheOwl/Name.txt",
    [ARTIFACT_CELESTIAL_JUSTICAR_ARMOR]      = "/Text/Game/Artifacts/CelestialJusticarArmor/Name.txt",
    [ARTIFACT_VIKING_HATCHET]                = "/Text/Game/Artifacts/VikingHatchet/Name.txt",
    [ARTIFACT_ORB_OF_AIR]                    = "/Text/Game/Artifacts/OrbOfAir/Name.txt",
    [ARTIFACT_ORB_OF_EARTH]                  = "/Text/Game/Artifacts/OrbOfEarth/Name.txt",
    [ARTIFACT_ORB_OF_FIRE]                   = "/Text/Game/Artifacts/OrbOfFire/Name.txt",
    [ARTIFACT_ORB_OF_WATER]                  = "/Text/Game/Artifacts/OrbOfWater/Name.txt",
    [ARTIFACT_OGRE_CLUB]                     = "/Text/Game/Artifacts/OgreClub/Name.txt",
    [ARTIFACT_OGRE_SHIELD]                   = "/Text/Game/Artifacts/OgreShield/Name.txt",
    [ARTIFACT_SHIELD_OF_THE_DWARVEN_KINGS]   = "/Text/Game/Artifacts/ShieldOfTheDwarvenKings/Name.txt",
}





log.trace("Loaded texts.lua")
