
CREATURE_UNKNOWN = 0
CREATURE_PEASANT = 1
CREATURE_MILITIAMAN = 2
CREATURE_ARCHER = 3
CREATURE_MARKSMAN = 4
CREATURE_FOOTMAN = 5
CREATURE_SWORDSMAN = 6
CREATURE_GRIFFIN = 7
CREATURE_ROYAL_GRIFFIN = 8
CREATURE_PRIEST = 9
CREATURE_CLERIC = 10
CREATURE_CAVALIER = 11
CREATURE_PALADIN = 12
CREATURE_ANGEL = 13
CREATURE_ARCHANGEL = 14
CREATURE_FAMILIAR = 15
CREATURE_IMP = 16
CREATURE_DEMON = 17
CREATURE_HORNED_DEMON = 18
CREATURE_HELL_HOUND = 19
CREATURE_CERBERI = 20
CREATURE_SUCCUBUS = 21
CREATURE_INFERNAL_SUCCUBUS = 22
CREATURE_NIGHTMARE = 23
CREATURE_FRIGHTFUL_NIGHTMARE = 24
CREATURE_PIT_FIEND = 25
CREATURE_BALOR = 26
CREATURE_DEVIL = 27
CREATURE_ARCHDEVIL = 28
CREATURE_SKELETON = 29
CREATURE_SKELETON_ARCHER = 30
CREATURE_WALKING_DEAD = 31
CREATURE_ZOMBIE = 32
CREATURE_MANES = 33
CREATURE_GHOST = 34
CREATURE_VAMPIRE = 35
CREATURE_VAMPIRE_LORD = 36
CREATURE_LICH = 37
CREATURE_DEMILICH = 38
CREATURE_WIGHT = 39
CREATURE_WRAITH = 40
CREATURE_BONE_DRAGON = 41
CREATURE_SHADOW_DRAGON = 42
CREATURE_PIXIE = 43
CREATURE_SPRITE = 44
CREATURE_BLADE_JUGGLER = 45
CREATURE_WAR_DANCER = 46
CREATURE_WOOD_ELF = 47
CREATURE_GRAND_ELF = 48
CREATURE_DRUID = 49
CREATURE_DRUID_ELDER = 50
CREATURE_UNICORN = 51
CREATURE_WAR_UNICORN = 52
CREATURE_TREANT = 53
CREATURE_TREANT_GUARDIAN = 54
CREATURE_GREEN_DRAGON = 55
CREATURE_GOLD_DRAGON = 56
CREATURE_GREMLIN = 57
CREATURE_MASTER_GREMLIN = 58
CREATURE_STONE_GARGOYLE = 59
CREATURE_OBSIDIAN_GARGOYLE = 60
CREATURE_IRON_GOLEM = 61
CREATURE_STEEL_GOLEM = 62
CREATURE_MAGI = 63
CREATURE_ARCH_MAGI = 64
CREATURE_GENIE = 65
CREATURE_MASTER_GENIE = 66
CREATURE_RAKSHASA = 67
CREATURE_RAKSHASA_RUKH = 68
CREATURE_GIANT = 69
CREATURE_TITAN = 70
CREATURE_SCOUT = 71
CREATURE_ASSASSIN = 72
CREATURE_WITCH = 73
CREATURE_BLOOD_WITCH = 74
CREATURE_MINOTAUR = 75
CREATURE_MINOTAUR_KING = 76
CREATURE_RIDER = 77
CREATURE_RAVAGER = 78
CREATURE_HYDRA = 79
CREATURE_CHAOS_HYDRA = 80
CREATURE_MATRON = 81
CREATURE_MATRIARCH = 82
CREATURE_DEEP_DRAGON = 83
CREATURE_BLACK_DRAGON = 84
CREATURE_FIRE_ELEMENTAL = 85
CREATURE_WATER_ELEMENTAL = 86
CREATURE_EARTH_ELEMENTAL = 87
CREATURE_AIR_ELEMENTAL = 88
CREATURE_BLACK_KNIGHT = 89
CREATURE_DEATH_KNIGHT = 90
CREATURE_PHOENIX = 91
CREATURE_DEFENDER = 92
CREATURE_STOUT_DEFENDER = 93
CREATURE_AXE_FIGHTER = 94
CREATURE_AXE_THROWER = 95
CREATURE_BEAR_RIDER = 96
CREATURE_BLACKBEAR_RIDER = 97
CREATURE_BROWLER = 98
CREATURE_BERSERKER = 99
CREATURE_RUNE_MAGE = 100
CREATURE_FLAME_MAGE = 101
CREATURE_THANE = 102
CREATURE_WARLORD = 103
CREATURE_FIRE_DRAGON = 104
CREATURE_MAGMA_DRAGON = 105
CREATURE_LANDLORD = 106
CREATURE_LONGBOWMAN = 107
CREATURE_VINDICATOR = 108
CREATURE_BATTLE_GRIFFIN = 109
CREATURE_ZEALOT = 110
CREATURE_CHAMPION = 111
CREATURE_SERAPH = 112
CREATURE_WOLF = 113
CREATURE_ARCANE_EAGLE = 114
CREATURE_MANTICORE = 115
CREATURE_MUMMY = 116
CREATURE_GOBLIN = 117
CREATURE_GOBLIN_TRAPPER = 118
CREATURE_CENTAUR = 119
CREATURE_CENTAUR_NOMAD = 120
CREATURE_ORC_WARRIOR = 121
CREATURE_ORC_SLAYER = 122
CREATURE_SHAMAN = 123
CREATURE_SHAMAN_WITCH = 124
CREATURE_ORCCHIEF_BUTCHER = 125
CREATURE_ORCCHIEF_EXECUTIONER = 126
CREATURE_WYVERN = 127
CREATURE_WYVERN_POISONOUS = 128
CREATURE_CYCLOP = 129
CREATURE_CYCLOP_UNTAMED = 130
CREATURE_QUASIT = 131
CREATURE_HORNED_LEAPER = 132
CREATURE_FIREBREATHER_HOUND = 133
CREATURE_SUCCUBUS_SEDUCER = 134
CREATURE_HELLMARE = 135
CREATURE_PIT_SPAWN = 136
CREATURE_ARCH_DEMON = 137
CREATURE_STALKER = 138
CREATURE_BLOOD_WITCH_2 = 139
CREATURE_MINOTAUR_CAPTAIN = 140
CREATURE_BLACK_RIDER = 141
CREATURE_ACIDIC_HYDRA = 142
CREATURE_SHADOW_MISTRESS = 143
CREATURE_RED_DRAGON = 144
CREATURE_DRYAD = 145
CREATURE_BLADE_SINGER = 146
CREATURE_SHARP_SHOOTER = 147
CREATURE_HIGH_DRUID = 148
CREATURE_WHITE_UNICORN = 149
CREATURE_ANGER_TREANT = 150
CREATURE_RAINBOW_DRAGON = 151
CREATURE_SKELETON_WARRIOR = 152
CREATURE_DISEASE_ZOMBIE = 153
CREATURE_POLTERGEIST = 154
CREATURE_NOSFERATU = 155
CREATURE_LICH_MASTER = 156
CREATURE_BANSHEE = 157
CREATURE_HORROR_DRAGON = 158
CREATURE_GREMLIN_SABOTEUR = 159
CREATURE_MARBLE_GARGOYLE = 160
CREATURE_OBSIDIAN_GOLEM = 161
CREATURE_COMBAT_MAGE = 162
CREATURE_DJINN_VIZIER = 163
CREATURE_RAKSHASA_KSHATRI = 164
CREATURE_STORM_LORD = 165
CREATURE_STONE_DEFENDER = 166
CREATURE_HARPOONER = 167
CREATURE_WHITE_BEAR_RIDER = 168
CREATURE_BATTLE_RAGER = 169
CREATURE_FLAME_KEEPER = 170
CREATURE_THUNDER_THANE = 171
CREATURE_LAVA_DRAGON = 172
CREATURE_GOBLIN_DEFILER = 173
CREATURE_CENTAUR_MARADEUR = 174
CREATURE_ORC_WARMONGER = 175
CREATURE_SHAMAN_HAG = 176
CREATURE_ORCCHIEF_CHIEFTAIN = 177
CREATURE_WYVERN_PAOKAI = 178
CREATURE_CYCLOP_BLOODEYED = 179
CREATURE_180 = 180
CREATURE_LIZARDMAN = 181
CREATURE_BASILISK = 182
CREATURE_BEHEMOTH = 183
CREATURE_KRAKEN = 184
CREATURE_EINHERJAR = 187
CREATURE_SPITTING_SPIDER = 188
CREATURE_LEGENDARY_DRAGON = 189
CREATURE_DRUID_OF_THE_COUNCIL = 190
CREATURE_DREAD_KNIGHT = 191
CREATURE_DWARF_WORKER = 192
CREATURES_COUNT = 200


CREATURES = {
    [CREATURE_PEASANT]          = {HAVEN, 1},         [CREATURE_MILITIAMAN]           = {HAVEN, 1},         [CREATURE_LANDLORD ]          = {HAVEN, 1},
    [CREATURE_ARCHER]           = {HAVEN, 2},         [CREATURE_MARKSMAN]             = {HAVEN, 2},         [CREATURE_LONGBOWMAN]         = {HAVEN, 2},
    [CREATURE_FOOTMAN]          = {HAVEN, 3},         [CREATURE_SWORDSMAN]            = {HAVEN, 3},         [CREATURE_VINDICATOR]         = {HAVEN, 3},
    [CREATURE_GRIFFIN]          = {HAVEN, 4},         [CREATURE_ROYAL_GRIFFIN]        = {HAVEN, 4},         [CREATURE_BATTLE_GRIFFIN]     = {HAVEN, 4},
    [CREATURE_PRIEST]           = {HAVEN, 5},         [CREATURE_CLERIC]               = {HAVEN, 5},         [CREATURE_ZEALOT]             = {HAVEN, 5},
    [CREATURE_CAVALIER]         = {HAVEN, 6},         [CREATURE_PALADIN]              = {HAVEN, 6},         [CREATURE_CHAMPION]           = {HAVEN, 6},
    [CREATURE_ANGEL]            = {HAVEN, 7},         [CREATURE_ARCHANGEL]            = {HAVEN, 7},         [CREATURE_SERAPH]             = {HAVEN, 7},
    [CREATURE_BLADE_JUGGLER]    = {PRESERVE, 1},      [CREATURE_WAR_DANCER]           = {PRESERVE, 1},      [CREATURE_BLADE_SINGER]       = {PRESERVE, 1},
    [CREATURE_PIXIE]            = {PRESERVE, 2},      [CREATURE_SPRITE]               = {PRESERVE, 2},      [CREATURE_DRYAD]              = {PRESERVE, 2},
    [CREATURE_WOOD_ELF]         = {PRESERVE, 3},      [CREATURE_GRAND_ELF]            = {PRESERVE, 3},      [CREATURE_SHARP_SHOOTER]      = {PRESERVE, 3},
    [CREATURE_DRUID]            = {PRESERVE, 4},      [CREATURE_DRUID_ELDER]          = {PRESERVE, 4},      [CREATURE_HIGH_DRUID]         = {PRESERVE, 4},
    [CREATURE_UNICORN]          = {PRESERVE, 5},      [CREATURE_WAR_UNICORN]          = {PRESERVE, 5},      [CREATURE_WHITE_UNICORN]      = {PRESERVE, 5},
    [CREATURE_TREANT]           = {PRESERVE, 6},      [CREATURE_TREANT_GUARDIAN]      = {PRESERVE, 6},      [CREATURE_ANGER_TREANT]       = {PRESERVE, 6},
    [CREATURE_GREEN_DRAGON]     = {PRESERVE, 7},      [CREATURE_GOLD_DRAGON]          = {PRESERVE, 7},      [CREATURE_RAINBOW_DRAGON]     = {PRESERVE, 7},
    [CREATURE_GREMLIN]          = {ACADEMY, 1},       [CREATURE_MASTER_GREMLIN]       = {ACADEMY, 1},       [CREATURE_GREMLIN_SABOTEUR]   = {ACADEMY, 1},
    [CREATURE_STONE_GARGOYLE]   = {ACADEMY, 2},       [CREATURE_OBSIDIAN_GARGOYLE]    = {ACADEMY, 2},       [CREATURE_MARBLE_GARGOYLE]    = {ACADEMY, 2},
    [CREATURE_IRON_GOLEM]       = {ACADEMY, 3},       [CREATURE_STEEL_GOLEM]          = {ACADEMY, 3},       [CREATURE_OBSIDIAN_GOLEM]     = {ACADEMY, 3},
    [CREATURE_MAGI]             = {ACADEMY, 4},       [CREATURE_ARCH_MAGI]            = {ACADEMY, 4},       [CREATURE_COMBAT_MAGE]        = {ACADEMY, 4},
    [CREATURE_GENIE]            = {ACADEMY, 5},       [CREATURE_MASTER_GENIE]         = {ACADEMY, 5},       [CREATURE_DJINN_VIZIER]       = {ACADEMY, 5},
    [CREATURE_RAKSHASA]         = {ACADEMY, 6},       [CREATURE_RAKSHASA_RUKH]        = {ACADEMY, 6},       [CREATURE_RAKSHASA_KSHATRI]   = {ACADEMY, 6},
    [CREATURE_GIANT]            = {ACADEMY, 7},       [CREATURE_TITAN]                = {ACADEMY, 7},       [CREATURE_STORM_LORD]         = {ACADEMY, 7},
    [CREATURE_DEFENDER]         = {FORTRESS, 1},      [CREATURE_STOUT_DEFENDER]       = {FORTRESS, 1},      [CREATURE_STONE_DEFENDER]     = {FORTRESS, 1},
    [CREATURE_AXE_FIGHTER]      = {FORTRESS, 2},      [CREATURE_AXE_THROWER]          = {FORTRESS, 2},      [CREATURE_HARPOONER]          = {FORTRESS, 2},
    [CREATURE_BROWLER]          = {FORTRESS, 3},      [CREATURE_BERSERKER]            = {FORTRESS, 3},      [CREATURE_BATTLE_RAGER]       = {FORTRESS, 3},
    [CREATURE_BEAR_RIDER]       = {FORTRESS, 4},      [CREATURE_BLACKBEAR_RIDER]      = {FORTRESS, 4},      [CREATURE_WHITE_BEAR_RIDER]   = {FORTRESS, 4},
    [CREATURE_RUNE_MAGE]        = {FORTRESS, 5},      [CREATURE_FLAME_MAGE]           = {FORTRESS, 5},      [CREATURE_FLAME_KEEPER]       = {FORTRESS, 5},
    [CREATURE_THANE]            = {FORTRESS, 6},      [CREATURE_WARLORD]              = {FORTRESS, 6},      [CREATURE_THUNDER_THANE]      = {FORTRESS, 6},
    [CREATURE_FIRE_DRAGON]      = {FORTRESS, 7},      [CREATURE_MAGMA_DRAGON]         = {FORTRESS, 7},      [CREATURE_LAVA_DRAGON]        = {FORTRESS, 7},
    [CREATURE_SKELETON]         = {NECROPOLIS, 1},    [CREATURE_SKELETON_ARCHER]      = {NECROPOLIS, 1},    [CREATURE_SKELETON_WARRIOR]   = {NECROPOLIS, 1},
    [CREATURE_WALKING_DEAD]     = {NECROPOLIS, 2},    [CREATURE_ZOMBIE]               = {NECROPOLIS, 2},    [CREATURE_DISEASE_ZOMBIE]     = {NECROPOLIS, 2},
    [CREATURE_MANES]            = {NECROPOLIS, 3},    [CREATURE_GHOST]                = {NECROPOLIS, 3},    [CREATURE_POLTERGEIST]        = {NECROPOLIS, 3},
    [CREATURE_VAMPIRE]          = {NECROPOLIS, 4},    [CREATURE_VAMPIRE_LORD]         = {NECROPOLIS, 4},    [CREATURE_NOSFERATU]          = {NECROPOLIS, 4},
    [CREATURE_LICH]             = {NECROPOLIS, 5},    [CREATURE_DEMILICH]             = {NECROPOLIS, 5},    [CREATURE_LICH_MASTER]        = {NECROPOLIS, 5},
    [CREATURE_BLACK_KNIGHT]     = {NECROPOLIS, 6},    [CREATURE_DREAD_KNIGHT]         = {NECROPOLIS, 6},    [CREATURE_DEATH_KNIGHT]       = {NECROPOLIS, 6},
    [CREATURE_WIGHT]            = {NECROPOLIS, 7},    [CREATURE_WRAITH]               = {NECROPOLIS, 7},    [CREATURE_BANSHEE]            = {NECROPOLIS, 7},
    [CREATURE_FAMILIAR]         = {INFERNO, 1},       [CREATURE_IMP]                  = {INFERNO, 1},       [CREATURE_QUASIT]             = {INFERNO, 1},
    [CREATURE_DEMON]            = {INFERNO, 2},       [CREATURE_HORNED_DEMON]         = {INFERNO, 2},       [CREATURE_HORNED_LEAPER]      = {INFERNO, 2},
    [CREATURE_HELL_HOUND]       = {INFERNO, 3},       [CREATURE_CERBERI]              = {INFERNO, 3},       [CREATURE_FIREBREATHER_HOUND] = {INFERNO, 3},
    [CREATURE_SUCCUBUS]         = {INFERNO, 4},       [CREATURE_INFERNAL_SUCCUBUS]    = {INFERNO, 4},       [CREATURE_SUCCUBUS_SEDUCER]   = {INFERNO, 4},
    [CREATURE_NIGHTMARE]        = {INFERNO, 5},       [CREATURE_FRIGHTFUL_NIGHTMARE]  = {INFERNO, 5},       [CREATURE_HELLMARE]           = {INFERNO, 5},
    [CREATURE_PIT_FIEND]        = {INFERNO, 6},       [CREATURE_BALOR]                = {INFERNO, 6},       [CREATURE_PIT_SPAWN]          = {INFERNO, 6},
    [CREATURE_DEVIL]            = {INFERNO, 7},       [CREATURE_ARCHDEVIL]            = {INFERNO, 7},       [CREATURE_ARCH_DEMON]         = {INFERNO, 7},
    [CREATURE_SCOUT]            = {DUNGEON, 1},       [CREATURE_ASSASSIN]             = {DUNGEON, 1},       [CREATURE_STALKER]            = {DUNGEON, 1},
    [CREATURE_WITCH]            = {DUNGEON, 2},       [CREATURE_BLOOD_WITCH]          = {DUNGEON, 2},       [CREATURE_BLOOD_WITCH_2]      = {DUNGEON, 2},
    [CREATURE_MINOTAUR]         = {DUNGEON, 3},       [CREATURE_MINOTAUR_KING]        = {DUNGEON, 3},       [CREATURE_MINOTAUR_CAPTAIN]   = {DUNGEON, 3},
    [CREATURE_RIDER]            = {DUNGEON, 4},       [CREATURE_RAVAGER]              = {DUNGEON, 4},       [CREATURE_BLACK_RIDER]        = {DUNGEON, 4},
    [CREATURE_MATRON]           = {DUNGEON, 5},       [CREATURE_MATRIARCH]            = {DUNGEON, 5},       [CREATURE_SHADOW_MISTRESS]    = {DUNGEON, 5},
    [CREATURE_HYDRA]            = {DUNGEON, 6},       [CREATURE_CHAOS_HYDRA]          = {DUNGEON, 6},       [CREATURE_ACIDIC_HYDRA]       = {DUNGEON, 6},
    [CREATURE_DEEP_DRAGON]      = {DUNGEON, 7},       [CREATURE_BLACK_DRAGON]         = {DUNGEON, 7},       [CREATURE_RED_DRAGON]         = {DUNGEON, 7},
    [CREATURE_GOBLIN]           = {STRONGHOLD, 1},    [CREATURE_GOBLIN_TRAPPER]       = {STRONGHOLD, 1},    [CREATURE_GOBLIN_DEFILER]     = {STRONGHOLD, 1},
    [CREATURE_SHAMAN]           = {STRONGHOLD, 2},    [CREATURE_SHAMAN_WITCH]         = {STRONGHOLD, 2},    [CREATURE_SHAMAN_HAG]         = {STRONGHOLD, 2},
    [CREATURE_ORC_WARRIOR]      = {STRONGHOLD, 3},    [CREATURE_ORC_SLAYER]           = {STRONGHOLD, 3},    [CREATURE_ORC_WARMONGER]      = {STRONGHOLD, 3},
    [CREATURE_CENTAUR]          = {STRONGHOLD, 4},    [CREATURE_CENTAUR_NOMAD]        = {STRONGHOLD, 4},    [CREATURE_CENTAUR_MARADEUR]   = {STRONGHOLD, 4},
    [CREATURE_ORCCHIEF_BUTCHER] = {STRONGHOLD, 5},    [CREATURE_ORCCHIEF_EXECUTIONER] = {STRONGHOLD, 5},    [CREATURE_ORCCHIEF_CHIEFTAIN] = {STRONGHOLD, 5},
    [CREATURE_WYVERN]           = {STRONGHOLD, 6},    [CREATURE_WYVERN_POISONOUS]     = {STRONGHOLD, 6},    [CREATURE_WYVERN_PAOKAI]      = {STRONGHOLD, 6},
    [CREATURE_CYCLOP]           = {STRONGHOLD, 7},    [CREATURE_CYCLOP_UNTAMED]       = {STRONGHOLD, 7},    [CREATURE_CYCLOP_BLOODEYED]   = {STRONGHOLD, 7},
    [CREATURE_BONE_DRAGON]      = {NECROPOLIS, 7},    [CREATURE_SHADOW_DRAGON]        = {NECROPOLIS, 7},    [CREATURE_HORROR_DRAGON]      = {NECROPOLIS, 7},
    [CREATURE_WOLF]             = {NEUTRAL, 3},       [CREATURE_MUMMY]                = {NEUTRAL, 3},       [CREATURE_MANTICORE]          = {NEUTRAL, 5},
    [CREATURE_ARCANE_EAGLE]     = {NEUTRAL, 6},       [CREATURE_PHOENIX]              = {NEUTRAL, 7},
    [CREATURE_AIR_ELEMENTAL]    = {NEUTRAL, 5},       [CREATURE_EARTH_ELEMENTAL]      = {NEUTRAL, 5},
    [CREATURE_WATER_ELEMENTAL]  = {NEUTRAL, 5},       [CREATURE_FIRE_ELEMENTAL]       = {NEUTRAL, 5},
    -- NCF
    [CREATURE_DRUID_OF_THE_COUNCIL] = {PRESERVE, 4},
    [CREATURE_DWARF_WORKER]     = {FORTRESS, 1},
    [CREATURE_LIZARDMAN]        = {NEUTRAL, 2},       [CREATURE_BASILISK]             = {NEUTRAL, 1},       [CREATURE_SPITTING_SPIDER]    = {NEUTRAL, 3},
    [CREATURE_BEHEMOTH]         = {NEUTRAL, 7},       [CREATURE_KRAKEN]               = {NEUTRAL, 7},       [CREATURE_EINHERJAR]          = {NEUTRAL, 7},
    [CREATURE_LEGENDARY_DRAGON] = {NEUTRAL, 8},
}


CREATURES_BY_FACTION = {
    [HAVEN] = {
        [1] = {CREATURE_PEASANT, CREATURE_MILITIAMAN, CREATURE_LANDLORD},
        [2] = {CREATURE_ARCHER, CREATURE_MARKSMAN, CREATURE_LONGBOWMAN},
        [3] = {CREATURE_FOOTMAN, CREATURE_SWORDSMAN, CREATURE_VINDICATOR},
        [4] = {CREATURE_GRIFFIN, CREATURE_ROYAL_GRIFFIN, CREATURE_BATTLE_GRIFFIN},
        [5] = {CREATURE_PRIEST, CREATURE_CLERIC, CREATURE_ZEALOT},
        [6] = {CREATURE_CAVALIER, CREATURE_PALADIN, CREATURE_CHAMPION},
        [7] = {CREATURE_ANGEL, CREATURE_ARCHANGEL, CREATURE_SERAPH},
    },
    [PRESERVE] = {
        [1] = {CREATURE_BLADE_JUGGLER, CREATURE_WAR_DANCER, CREATURE_BLADE_SINGER},
        [2] = {CREATURE_PIXIE, CREATURE_SPRITE, CREATURE_DRYAD},
        [3] = {CREATURE_WOOD_ELF, CREATURE_GRAND_ELF, CREATURE_SHARP_SHOOTER},
        [4] = {CREATURE_DRUID, CREATURE_DRUID_ELDER, CREATURE_HIGH_DRUID},
        [5] = {CREATURE_UNICORN, CREATURE_WAR_UNICORN, CREATURE_WHITE_UNICORN},
        [6] = {CREATURE_TREANT, CREATURE_TREANT_GUARDIAN, CREATURE_ANGER_TREANT},
        [7] = {CREATURE_GREEN_DRAGON, CREATURE_GOLD_DRAGON, CREATURE_RAINBOW_DRAGON},
    },
    [ACADEMY] = {
        [1] = {CREATURE_GREMLIN, CREATURE_MASTER_GREMLIN, CREATURE_GREMLIN_SABOTEUR},
        [2] = {CREATURE_STONE_GARGOYLE, CREATURE_OBSIDIAN_GARGOYLE, CREATURE_MARBLE_GARGOYLE},
        [3] = {CREATURE_IRON_GOLEM, CREATURE_STEEL_GOLEM, CREATURE_OBSIDIAN_GOLEM},
        [4] = {CREATURE_MAGI, CREATURE_ARCH_MAGI, CREATURE_COMBAT_MAGE},
        [5] = {CREATURE_GENIE, CREATURE_MASTER_GENIE, CREATURE_DJINN_VIZIER},
        [6] = {CREATURE_RAKSHASA, CREATURE_RAKSHASA_RUKH, CREATURE_RAKSHASA_KSHATRI},
        [7] = {CREATURE_GIANT, CREATURE_TITAN, CREATURE_STORM_LORD},
    },
    [FORTRESS] = {
        [1] = {CREATURE_DEFENDER, CREATURE_STOUT_DEFENDER, CREATURE_STONE_DEFENDER},
        [2] = {CREATURE_AXE_FIGHTER, CREATURE_AXE_THROWER, CREATURE_HARPOONER},
        [3] = {CREATURE_BROWLER, CREATURE_BERSERKER, CREATURE_BATTLE_RAGER},
        [4] = {CREATURE_BEAR_RIDER, CREATURE_BLACKBEAR_RIDER, CREATURE_WHITE_BEAR_RIDER},
        [5] = {CREATURE_RUNE_MAGE, CREATURE_FLAME_MAGE, CREATURE_FLAME_KEEPER},
        [6] = {CREATURE_THANE, CREATURE_WARLORD, CREATURE_THUNDER_THANE},
        [7] = {CREATURE_FIRE_DRAGON, CREATURE_MAGMA_DRAGON, CREATURE_LAVA_DRAGON},
    },
    [NECROPOLIS] = {
        [1] = {CREATURE_SKELETON, CREATURE_SKELETON_ARCHER, CREATURE_SKELETON_WARRIOR},
        [2] = {CREATURE_WALKING_DEAD, CREATURE_ZOMBIE, CREATURE_DISEASE_ZOMBIE},
        [3] = {CREATURE_MANES, CREATURE_GHOST, CREATURE_POLTERGEIST},
        [4] = {CREATURE_VAMPIRE, CREATURE_VAMPIRE_LORD, CREATURE_NOSFERATU},
        [5] = {CREATURE_LICH, CREATURE_DEMILICH, CREATURE_LICH_MASTER},
        [6] = {CREATURE_BLACK_KNIGHT, CREATURE_DREAD_KNIGHT, CREATURE_DEATH_KNIGHT},
        [7] = {CREATURE_WIGHT, CREATURE_WRAITH, CREATURE_BANSHEE},
    },
    [INFERNO] = {
        [1] = {CREATURE_FAMILIAR, CREATURE_IMP, CREATURE_QUASIT},
        [2] = {CREATURE_DEMON, CREATURE_HORNED_DEMON, CREATURE_HORNED_LEAPER},
        [3] = {CREATURE_HELL_HOUND, CREATURE_CERBERI, CREATURE_FIREBREATHER_HOUND},
        [4] = {CREATURE_SUCCUBUS, CREATURE_INFERNAL_SUCCUBUS, CREATURE_SUCCUBUS_SEDUCER},
        [5] = {CREATURE_NIGHTMARE, CREATURE_FRIGHTFUL_NIGHTMARE, CREATURE_HELLMARE},
        [6] = {CREATURE_PIT_FIEND, CREATURE_BALOR, CREATURE_PIT_SPAWN},
        [7] = {CREATURE_DEVIL, CREATURE_ARCHDEVIL, CREATURE_ARCH_DEMON},
    },
    [DUNGEON] = {
        [1] = {CREATURE_SCOUT, CREATURE_ASSASSIN, CREATURE_STALKER},
        [2] = {CREATURE_WITCH, CREATURE_BLOOD_WITCH, CREATURE_BLOOD_WITCH_2},
        [3] = {CREATURE_MINOTAUR, CREATURE_MINOTAUR_KING, CREATURE_MINOTAUR_CAPTAIN},
        [4] = {CREATURE_RIDER, CREATURE_RAVAGER, CREATURE_BLACK_RIDER},
        [5] = {CREATURE_MATRON, CREATURE_MATRIARCH, CREATURE_SHADOW_MISTRESS},
        [6] = {CREATURE_HYDRA, CREATURE_CHAOS_HYDRA, CREATURE_ACIDIC_HYDRA},
        [7] = {CREATURE_DEEP_DRAGON, CREATURE_BLACK_DRAGON, CREATURE_RED_DRAGON},
    },
    [STRONGHOLD] = {
        [1] = {CREATURE_GOBLIN, CREATURE_GOBLIN_TRAPPER, CREATURE_GOBLIN_DEFILER},
        [2] = {CREATURE_SHAMAN, CREATURE_SHAMAN_WITCH, CREATURE_SHAMAN_HAG},
        [3] = {CREATURE_ORC_WARRIOR, CREATURE_ORC_SLAYER, CREATURE_ORC_WARMONGER},
        [4] = {CREATURE_CENTAUR, CREATURE_CENTAUR_NOMAD, CREATURE_CENTAUR_MARADEUR},
        [5] = {CREATURE_ORCCHIEF_BUTCHER, CREATURE_ORCCHIEF_EXECUTIONER, CREATURE_ORCCHIEF_CHIEFTAIN},
        [6] = {CREATURE_WYVERN, CREATURE_WYVERN_POISONOUS, CREATURE_WYVERN_PAOKAI},
        [7] = {CREATURE_CYCLOP, CREATURE_CYCLOP_UNTAMED, CREATURE_CYCLOP_BLOODEYED},
    },
}


-- log("Loaded creatures.lua")
ROUTINES_LOADED[1] = 1
