
-- Skill type IDs
--
SKILL_NONE = 0
SKILL_LOGISTICS = 1
SKILL_WARFARE = 2
SKILL_LEARNING = 3
PERK_MOTIVATION = 4
PERK_PRECISION = 5
SKILL_OFFENCE = 6
SKILL_DEFENSE = 7
SKILL_SORCERY = 8
SKILL_DESTRUCTIVE_MAGIC = 9
SKILL_DARK_MAGIC = 10
SKILL_LIGHT_MAGIC = 11
SKILL_NATURAL_MAGIC = 12
SKILL_COMBAT = 13
SKILL_GATING = 14
SKILL_NECROMANCY = 15
SKILL_AVENGER = 16
SKILL_ARTIFICIER = 17
SKILL_ARCANISM = 18
PERK_PATHFINDING = 19
PERK_SCOUTING = 20
SKILL_GOVERNANCE = 21
PERK_ANATOMY = 22
PERK_BALLISTICS = 23
PERK_HOUNDMASTERS = 24
TODO_25 = 25 -- unused
PERK_SCHOLAR = 26
PERK_INTUITION = 27
PERK_RECRUITMENT = 28
PERK_ESTATES = 29
PERK_DIPLOMACY = 30
PERK_MAGIC_RESISTANCE = 31
PERK_EXPERTISE = 32
PERK_GEOLOGY = 33
PERK_TACTICS = 34
PERK_ARCHERY = 35
PERK_BATTLE_FRENZY = 36
PERK_PROTECTION = 37
PERK_EVASION = 38
PERK_TOUGHNESS = 39
PERK_OCCULTISM = 40
PERK_MAGIC_INSIGHT = 41
PERK_ARCANE_INITIATION = 42
PERK_FROST_POWER = 43
PERK_BLAZE_POWER = 44
SPEC_THUNDER_POWER = 45
PERK_SPREAD_CURSE = 46
SPEC_DARKNESS_AFFINITY = 47
PERK_SPREAD_PAIN = 48
SPEC_DIVINE_BLESSING = 49
PERK_AURA_OF_PROTECTION = 50
PERK_AURA_OF_ENERGY = 51
SPEC_MASTER_OF_QUAKES = 52
PERK_CONJURER = 53
SKILL_INNATES = 54
PERK_RETALIATION_STRIKE = 55
PERK_PRAYER = 56
PERK_EXPERT_TRAINER = 57
PERK_CONSUME_CORPSE = 58
PERK_HELLFIRE = 59
PERK_AVENGING_STRIKE = 60
SKILL_COURAGE = 61
PERK_ETERNAL_SERVITUDE = 62
PERK_BANSHEE_HOWL = 63
SPEC_RAIN_OF_ARROWS = 64
PERK_SNIPE_DEAD = 65
PERK_IMBUE_ARROW = 66
PERK_MAGIC_BOND = 67
PERK_MELT_ARTIFACT = 68
PERK_MAGIC_MIRROR = 69
PERK_EMPOWERED_SPELLS = 70
PERK_MEDITATION = 71
PERK_ELEMENTAL_VISION = 72
PERK_FAMILIAR_LAND = 73
PERK_RAPIDFIRE = 74
PERK_ENCOURAGE = 75
PERK_RETRIBUTION = 76
PERK_HOLD_GROUND = 77
PERK_GUARDIAN_ANGEL = 78
SPEC_ENLIGHTENED = 79
PERK_INDUSTRY = 80
PERK_INFUSION = 81
PERK_FIERY_WRATH = 82
PERK_PARIAH = 83
PERK_ELEMENTAL_BALANCE = 84
PERK_HOLY_CHARGE = 85
PERK_SWIFT_GATING = 86
PERK_EXALTATION = 87
PERK_WARRIORS_OF_THE_SEA = 88
PERK_GATE_MASTER = 89
PERK_SWARMING_GATE = 90
PERK_BRUTALITY = 91
PERK_COMMANDER = 92
PERK_RAGE_AWAKENING = 93
PERK_SEARING_FIRES = 94
SPEC_VAMPIRISM = 95
PERK_BURNING_BLOOD = 96
PERK_WARRIORS_OF_THE_MAGMA = 97
PERK_URGASHS_CALL = 98
PERK_SIEGE = 99 --unused
PERK_PLAGUE_TENT = 100
PERK_LORD_OF_UNDEAD = 101
PERK_HERALD_OF_DEATH = 102
PERK_DEAD_MANS_CURSE = 103
PERK_COLD_STEEL = 104
PERK_CHILLING_BONES = 105
PERK_SPELLPROOF_BONES = 106
PERK_DEADLY_COLD = 107
PERK_SPIRIT_LINK = 108
PERK_TWILIGHT = 109
PERK_HAUNTING = 110
SPEC_BATTLE_ARDOR = 111
PERK_SILENT_TRACKER = 112
PERK_IMBUE_BALLISTA = 113
PERK_KNOW_YOUR_ENEMY = 114
PERK_BATTLE_COMMANDER = 115
PERK_FATAL_STRIKES = 116
PERK_RAGE_OF_THE_FOREST = 117
PERK_LAST_STAND = 118
PERK_WITCHCRAFT = 119
SPEC_OVERHEAT = 120
PERK_SOIL_BURN = 121
PERK_STORM_WIND = 122
PERK_FOG_VEIL = 123
SKILL_SPIRITISM = 124
PERK_MARCH_OF_THE_GOLEMS = 125
PERK_REMOTE_CONTROL = 126
SKILL_ULTIMATE = 127
PERK_ARTIFICIAL_GLORY = 128
PERK_SPOILS_OF_WAR = 129
PERK_FLAMING_ARROWS = 130
PERK_SEAL_OF_PROTECTION = 131
PERK_COUNTERSPELL = 132
PERK_SAP_MAGIC = 133
PERK_SUPRESS_DARK = 134
PERK_SUPRESS_LIGHT = 135
PERK_BANISH = 136
PERK_OMNISCIENCE = 137
PERK_TELEPORT_ASSAULT = 138
PERK_WARRIORS_OF_THE_MOUNTAIN = 139
PERK_GRADUATE = 140
PERK_SWIFTNESS = 141
PERK_LUCKY_CASTER = 142
PERK_POWER_OF_HASTE = 143
PERK_POWER_OF_STONE = 144
PERK_CHAOTIC_SPELLS = 145
SPEC_FORBIDDEN_POWER = 146
PERK_SECRETS_OF_DESTRUCT = 147
PERK_ARCANE_BRILLANCE = 148
PERK_OBLITERATION = 149
PERK_RAGE_OF_THE_ELEMENTS = 150
SKILL_RUNELORE = 151
PERK_REFRESH_RUNE = 152
PERK_GREATER_RUNE = 153
PERK_FINE_RUNE = 154
PERK_ARCANE_EXCELLENCE = 155
PERK_TECHNICAL_STAFF = 156
PERK_TAP_RUNES = 157
PERK_RUNIC_ATTUNEMENT = 158
PERK_DETERMINATION = 159
PERK_OFFENSIVE_FORMATION = 160
PERK_DEFENSIVE_FORMATION = 161
PERK_DISTRACT = 162
PERK_IGNITE = 163
PERK_TENACITY = 164
PERK_VENGEFUL_LIGHT = 165
PERK_RUNIC_SHIELD = 166
PERK_BULWARK_RUNE = 167
PERK_SNATCH = 168
PERK_MENTORING = 169
PERK_EMPATHY = 170
PERK_PREPARATION = 171
SKILL_BLOOD_RAGE = 172
PERK_MIGHT_OVER_MAGIC = 173
PERK_MEMORY_OF_OUR_BLOOD = 174
PERK_COORDINATION = 175
PERK_ORCISH_FURY = 176
PERK_WAR_PATH = 177
PERK_BATTLE_ELATION = 178
PERK_PAIN_KILLER = 179
PERK_STUNNING_BLOW = 180
PERK_DEFEND_US_ALL = 181
PERK_GOBLIN_SUPPORT = 182
SKILL_BARBARIAN_LEARNING = 183 --unused
PERK_BLOODFIRE = 184
SKILL_TRAINING = 185
PERK_SHEER_STRENGTH = 186
SKILL_VOICE = 187
PERK_VOICE_TRAINING = 188
PERK_MIGHTY_SHOUT = 189
PERK_BLOODLUST = 190
PERK_TALETELLERS = 191
PERK_CHARISMA = 192
PERK_ONSLAUGHT = 193
PERK_SIPHON_GRACE = 194
PERK_GET_STRONGER = 195
PERK_GET_WISER = 196
SPEC_SYLANNAS_BENEDICTION = 197
SKILL_LEADERSHIP = 198
SKILL_SHATTER_MAGIC = 199
PERK_GEAR_UP = 200
PERK_HEROES_LEGACY = 201
PERK_MYTHOLOGY = 202
PERK_WARRIORS_OF_THE_SKY = 203
PERK_STAMINA = 204
SPEC_ROYAL_CHARGE = 205
PERK_MAGIC_FILTER = 206
PERK_BACK_TO_THE_VOID = 207
PERK_BARBARIAN_ANCIENT_SMITHY = 208 --unused
SPEC_VAMPIRISM_2 = 209 --unused
PERK_SCORCHING_EARTH = 210
PERK_BARBARIAN_FOG_VEIL = 211 --unused
PERK_INTELLIGENCE = 212
PERK_BARBARIAN_MYSTICISM = 213 --unused
PERK_BARBARIAN_ELITE_CASTERS = 214 --unused
PERK_BARBARIAN_STORM_WIND = 215 --unused
PERK_FIRE_RESISTANCE = 216
PERK_MANA_BURST = 217
PERK_BARBARIAN_DISTRACT = 218 --unused
PERK_DARK_REVELATION = 219
PERK_TALENTED_WARRIOR = 220


SKILLS_BY_FACTION = {
    [HAVEN]      = { base=SKILL_COURAGE, innate=PERK_FAMILIAR_LAND, ult=PERK_RETRIBUTION },
    [PRESERVE]   = { base=SKILL_AVENGER, innate=PERK_SILENT_TRACKER, ult=PERK_RAGE_OF_THE_FOREST },
    [FORTRESS]   = { base=SKILL_RUNELORE, innate=PERK_TENACITY, ult=PERK_BULWARK_RUNE },
    [ACADEMY]    = { base=SKILL_ARTIFICIER, innate=PERK_INFUSION, ult=PERK_OMNISCIENCE },
    [DUNGEON]    = { base=SKILL_ARCANISM, innate=PERK_ELEMENTAL_VISION, ult=PERK_RAGE_OF_THE_ELEMENTS },
    [NECROPOLIS] = { base=SKILL_NECROMANCY, innate=PERK_ETERNAL_SERVITUDE, ult=PERK_DEAD_MANS_CURSE },
    [INFERNO]    = { base=SKILL_GATING, innate=PERK_SOIL_BURN, ult=PERK_URGASHS_CALL },
    [STRONGHOLD] = { base=SKILL_BLOOD_RAGE, innate=PERK_SIEGE, ult=PERK_ORCISH_FURY },
}

SKILLS_COMMON = {
    SKILL_LOGISTICS, SKILL_WARFARE, SKILL_COMBAT, SKILL_TRAINING, SKILL_GOVERNANCE, SKILL_LEADERSHIP,
    SKILL_LIGHT_MAGIC, SKILL_DARK_MAGIC, SKILL_DESTRUCTIVE_MAGIC, SKILL_NATURAL_MAGIC, SKILL_SHATTER_MAGIC,
    SKILL_OFFENCE, SKILL_DEFENSE, SKILL_LEARNING, SKILL_SORCERY, SKILL_VOICE, SKILL_SPIRITISM,
}


-- Skill bonuses
--
_skillbonus_id = 0 
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_OFFENCE             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_DEFENSE             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_LEARNING            = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SORCERY             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_VOICE               = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_LIGHT_MAGIC         = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_DARK_MAGIC          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_NATURAL_MAGIC       = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_DESTRUCT_MAGIC      = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_COURAGE             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_AVENGER             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_ARTIFICIER          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SPIRITISM           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_PRECISION           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_HOLD_GROUND         = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_INTELLIGENCE        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_EXALTATION          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_ARCANE_EXCELLENCE   = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GRADUATE            = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_OCCULTISM           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SECRETS_OF_DESTRUCT = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GET_STRONGER        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GET_WISER           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_ONSLAUGHT           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_LAST_STAND          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_PATHFINDING         = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GEAR_UP             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_HEROES_LEGACY       = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_MYTHOLOGY           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_IMBUE_ARROW         = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_IMBUE_BALLISTA      = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_BATTLE_COMMANDER    = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_FINE_RUNE           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_REFRESH_RUNE        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GREATER_RUNE        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_LORD_OF_THE_UNDEAD  = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_DEFEND_US_ALL       = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SHEER_STRENGTH      = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_INFUSION            = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_ENLIGHTENED         = _skillbonus_id


-- log("Loaded skills.lua")
ROUTINES_LOADED[3] = 1
