
-- Skill type IDs
--
SKILL_NONE = 0
SKILL_LOGISTICS = 1
SKILL_WARFARE = 2
SKILL_LEARNING = 3
SKILL_COURAGE = 4
PERK_PRECISION = 5
SKILL_OFFENCE = 6
SKILL_DEFENSE = 7
SKILL_SORCERY = 8
SKILL_DESTRUCTIVE_MAGIC = 9
SKILL_DARK_MAGIC = 10
SKILL_LIGHT_MAGIC = 11
SKILL_NATURAL_MAGIC = 12
SKILL_COMBAT = 13
SKILL_GATING = 14
SKILL_NECROMANCY = 15
SKILL_AVENGER = 16
SKILL_ARTIFICIER = 17
SKILL_ARCANISM = 18
PERK_PATHFINDING = 19
PERK_SCOUTING = 20
SKILL_GOVERNANCE = 21
PERK_ANATOMY = 22
PERK_BALLISTICS = 23
PERK_HOUNDMASTERS = 24
PERK_INTELLIGENCE = 25
PERK_SCHOLAR = 26
PERK_INTUITION = 27
PERK_RECRUITMENT = 28
PERK_ESTATES = 29
PERK_DIPLOMACY = 30
PERK_SPELLBREAKER = 31
PERK_EXPERTISE = 32
PERK_GEOLOGY = 33
PERK_TACTICS = 34
PERK_ARCHERY = 35
PERK_BATTLE_FRENZY = 36
PERK_PROTECTION = 37
PERK_EVASION = 38
PERK_TOUGHNESS = 39
PERK_OCCULTISM = 40
PERK_MAGIC_INSIGHT = 41
PERK_ARCANE_INITIATION = 42
PERK_FROST_POWER = 43
PERK_BLAZE_POWER = 44
SPEC_THUNDER_POWER = 45
PERK_SPREAD_CURSE = 46
SPEC_DARKNESS_AFFINITY = 47
PERK_SPREAD_PAIN = 48
SPEC_DIVINE_BLESSING = 49
PERK_AURA_OF_PROTECTION = 50
PERK_AURA_OF_ENERGY = 51
SPEC_MASTER_OF_QUAKES = 52
PERK_CONJURER = 53
SKILL_INNATES = 54
PERK_RETALIATION_STRIKE = 55
PERK_PRAYER = 56
PERK_EXPERT_TRAINER = 57
PERK_CONSUME_CORPSE = 58
PERK_HELLFIRE = 59
PERK_AVENGING_STRIKE = 60
PERK_MOTIVATION = 61
PERK_ETERNAL_SERVITUDE = 62
PERK_BANSHEE_HOWL = 63
SPEC_RAIN_OF_ARROWS = 64
PERK_SNIPE_DEAD = 65
PERK_IMBUE_ARROW = 66
PERK_MAGIC_BOND = 67
PERK_MELT_ARTIFACT = 68
PERK_MAGIC_MIRROR = 69
PERK_EMPOWERED_SPELLS = 70
PERK_MEDITATION = 71
PERK_ELEMENTAL_VISION = 72
PERK_FAMILIAR_LAND = 73
PERK_RAPIDFIRE = 74
PERK_ENCOURAGE = 75
ULTI_RETRIBUTION = 76
PERK_HOLD_GROUND = 77
PERK_GUARDIAN_ANGEL = 78
SPEC_ENLIGHTENED = 79
PERK_INDUSTRY = 80
PERK_INFUSION = 81
PERK_FIERY_WRATH = 82
PERK_PARIAH = 83
PERK_ELEMENTAL_BALANCE = 84
PERK_HOLY_CHARGE = 85
PERK_SWIFT_GATING = 86
PERK_EXALTATION = 87
PERK_WARRIORS_OF_THE_SEA = 88
PERK_GATE_MASTER = 89
PERK_SWARMING_GATE = 90
PERK_BRUTALITY = 91
PERK_COMMANDER = 92
PERK_ABSOLUTE_MASTERY = 93
PERK_SEARING_FIRES = 94
SPEC_VAMPIRISM = 95
SPEC_BURNING_BLOOD = 96
PERK_WARRIORS_OF_THE_MAGMA = 97
ULTI_URGASHS_CALL = 98
PERK_SIEGE = 99 --unused catapult +move
PERK_PLAGUE_TENT = 100
PERK_LORD_OF_UNDEAD = 101
PERK_HERALD_OF_DEATH = 102
ULTI_DEAD_MANS_CURSE = 103
PERK_COLD_STEEL = 104
PERK_CHILLING_BONES = 105
PERK_SPELLPROOF_BONES = 106
PERK_DEADLY_COLD = 107
PERK_SPIRIT_LINK = 108
PERK_TWILIGHT = 109
PERK_HAUNTING = 110
SPEC_BATTLE_ARDOR = 111
PERK_SILENT_TRACKER = 112
PERK_IMBUE_BALLISTA = 113
PERK_KNOW_YOUR_ENEMY = 114
PERK_BATTLE_COMMANDER = 115
PERK_FATAL_STRIKES = 116
ULTI_RAGE_OF_THE_FOREST = 117
PERK_LAST_STAND = 118
PERK_WITCHCRAFT = 119
PERK_MANA_BURST = 120 -- unused
PERK_SOIL_BURN = 121
PERK_STORM_WIND = 122
PERK_FOG_VEIL = 123
SKILL_SPIRITISM = 124
PERK_MARCH_OF_THE_GOLEMS = 125
PERK_REMOTE_CONTROL = 126
PERK_ACADEMY_AWARD = 127 --unused +2sp 1000g
PERK_ARTIFICIAL_GLORY = 128
PERK_SPOILS_OF_WAR = 129
PERK_FLAMING_ARROWS = 130
PERK_SEAL_OF_PROTECTION = 131
PERK_COUNTERSPELL = 132
PERK_SAP_MAGIC = 133
PERK_STUN_TRAINING = 134
PERK_ASSAULT_TRAINING = 135
PERK_BANISH = 136
ULTI_OMNISCIENCE = 137
PERK_TELEPORT_ASSAULT = 138
PERK_WARRIORS_OF_THE_MOUNTAIN = 139
PERK_GRADUATE = 140
PERK_SWIFTNESS = 141
PERK_LUCKY_CASTER = 142
PERK_POWER_OF_HASTE = 143
PERK_POWER_OF_STONE = 144
PERK_CHAOTIC_SPELLS = 145
SPEC_FORBIDDEN_POWER = 146
PERK_SECRETS_OF_DESTRUCT = 147
PERK_ARCANE_BRILLANCE = 148
PERK_OBLITERATION = 149
ULTI_RAGE_OF_THE_ELEMENTS = 150
SKILL_RUNELORE = 151
PERK_REFRESH_RUNE = 152
PERK_GREATER_RUNE = 153
PERK_FINE_RUNE = 154
PERK_ARCANE_EXCELLENCE = 155
PERK_WARFARE_LOGISTICS = 156
PERK_TAP_RUNES = 157
PERK_RUNIC_ATTUNEMENT = 158
PERK_COUNTER_MAGIC = 159
PERK_OFFENSIVE_FORMATION = 160
PERK_DEFENSIVE_FORMATION = 161
PERK_INTIMIDATING_VOICE = 162
PERK_IGNITE = 163
PERK_TENACITY = 164
PERK_VENGEFUL_LIGHT = 165
PERK_RUNIC_SHIELD = 166
PERK_BULWARK_RUNE = 167
PERK_SNATCH = 168
PERK_MENTORING = 169
PERK_EMPATHY = 170
PERK_PREPARATION = 171
SKILL_BLOOD_RAGE = 172
PERK_DOMINANT_SHOUT = 173
PERK_MEMORY_OF_OUR_BLOOD = 174
PERK_COORDINATION = 175
ULTI_ORCISH_FURY = 176
PERK_WAR_PATH = 177
PERK_BATTLE_ELATION = 178
PERK_LUNG_WORKOUT = 179
PERK_STUNNING_BLOW = 180
PERK_DEFEND_US_ALL = 181
PERK_GOBLIN_SUPPORT = 182
PERK_RAGE_AWAKENING = 183
PERK_BLOODFIRE = 184
SKILL_TRAINING = 185
PERK_SHEER_STRENGTH = 186
SKILL_VOICE = 187
PERK_VOICE_TRAINING = 188
PERK_MIGHTY_SHOUT = 189
PERK_BLOODLUST = 190
PERK_TALETELLERS = 191
PERK_CHARISMA = 192
PERK_ONSLAUGHT = 193
PERK_SIPHON_GRACE = 194
PERK_REINFORCEMENT = 195
PERK_EMPIRICISM = 196
SPEC_SYLANNAS_BENEDICTION = 197
SKILL_LEADERSHIP = 198
SKILL_SHATTER_MAGIC = 199
PERK_GEAR_UP = 200
PERK_HEROES_LEGACY = 201
PERK_MYTHOLOGY = 202
PERK_WARRIORS_OF_THE_SKY = 203
PERK_STAMINA = 204
SPEC_ROYAL_CHARGE = 205
PERK_MAGIC_FILTER = 206
PERK_BACK_TO_THE_VOID = 207
PERK_CORRUPTION_IMMUNE = 208
PERK_ARMOR_PROTECTION = 209
PERK_SCORCHING_EARTH = 210
SKILL_DESPOTISM = 211
PERK_DEVOTION = 212
PERK_BATTLE_WRATH = 213
PERK_WAR_POLICY = 214
PERK_INFERNAL_PORTALS = 215
PERK_FIRE_RESISTANCE = 216
PERK_ADVANCED_BLOOD_RAGE = 217
PERK_UNLIMITED_RETALIATIONS = 218
PERK_FIERCE_RETALIATIONS = 219
SPEC_TALENTED_WARRIOR = 220
PERK_RUSH = 221
PERK_222 = 222
PERK_223 = 223
PERK_224 = 224
PERK_225 = 225
PERK_226 = 226
PERK_227 = 227
PERK_228 = 228
PERK_229 = 229
PERK_230 = 230
PERK_231 = 231
PERK_232 = 232
PERK_233 = 233
PERK_234 = 234
PERK_235 = 235
PERK_236 = 236
PERK_237 = 237
PERK_238 = 238
PERK_239 = 239
PERK_240 = 240
PERK_241 = 241
PERK_242 = 242
PERK_243 = 243
PERK_244 = 244
PERK_245 = 245
PERK_246 = 246
PERK_247 = 247
PERK_248 = 248
PERK_249 = 249
PERK_250 = 250
PERK_251 = 251
PERK_252 = 252
PERK_253 = 253
PERK_254 = 254


SKILLS_BY_FACTION = {
    [HAVEN]      = {
        base=SKILL_COURAGE, innate=PERK_FAMILIAR_LAND, ult=ULTI_RETRIBUTION,
        perks={PERK_PRAYER, PERK_EMPATHY, PERK_GUARDIAN_ANGEL, PERK_EXPERT_TRAINER, PERK_RETALIATION_STRIKE, PERK_HOLY_CHARGE}
    },
    [PRESERVE]   = {
        base=SKILL_AVENGER, innate=PERK_SILENT_TRACKER, ult=ULTI_RAGE_OF_THE_FOREST,
        perks={PERK_IMBUE_ARROW, PERK_IMBUE_BALLISTA, PERK_LUCKY_CASTER, PERK_SNIPE_DEAD, PERK_KNOW_YOUR_ENEMY, PERK_BATTLE_COMMANDER}
    },
    [FORTRESS]   = {
        base=SKILL_RUNELORE, innate=PERK_TENACITY, ult=PERK_BULWARK_RUNE,
        perks={PERK_FINE_RUNE, PERK_REFRESH_RUNE, PERK_GREATER_RUNE, PERK_TAP_RUNES, PERK_RUNIC_ATTUNEMENT, PERK_RUNIC_SHIELD}
    },
    [ACADEMY]    = {
        base=SKILL_ARTIFICIER, innate=PERK_INFUSION, ult=ULTI_OMNISCIENCE,
        perks={PERK_MELT_ARTIFACT, PERK_MAGIC_BOND, PERK_MAGIC_MIRROR, PERK_ARTIFICIAL_GLORY, PERK_MARCH_OF_THE_GOLEMS, PERK_REMOTE_CONTROL}
    },
    [DUNGEON]    = {
        base=SKILL_ARCANISM, innate=PERK_ELEMENTAL_VISION, ult=ULTI_RAGE_OF_THE_ELEMENTS,
        perks={PERK_EMPOWERED_SPELLS, PERK_CHAOTIC_SPELLS, PERK_OBLITERATION, PERK_POWER_OF_STONE, PERK_POWER_OF_HASTE, PERK_TELEPORT_ASSAULT}
    },
    [NECROPOLIS] = {
        base=SKILL_NECROMANCY, innate=PERK_ETERNAL_SERVITUDE, ult=ULTI_DEAD_MANS_CURSE,
        perks={PERK_BANSHEE_HOWL, PERK_HAUNTING, PERK_LORD_OF_UNDEAD, PERK_CHILLING_BONES, PERK_SPELLPROOF_BONES, PERK_HERALD_OF_DEATH}
    },
    [INFERNO]    = {
        base=SKILL_GATING, innate=PERK_SOIL_BURN, ult=ULTI_URGASHS_CALL,
        perks={PERK_SWIFT_GATING, PERK_GATE_MASTER, PERK_SWARMING_GATE, PERK_HELLFIRE, PERK_SEARING_FIRES, PERK_FIERY_WRATH}
    },
    [STRONGHOLD] = {
        base=SKILL_BLOOD_RAGE, innate=PERK_COMMANDER, ult=ULTI_ORCISH_FURY,
        perks={PERK_MEMORY_OF_OUR_BLOOD, PERK_BATTLE_ELATION, PERK_BLOODFIRE, PERK_GOBLIN_SUPPORT, PERK_DEFEND_US_ALL, PERK_SHEER_STRENGTH,
               PERK_WITCHCRAFT, PERK_TWILIGHT, PERK_RAGE_AWAKENING, PERK_ADVANCED_BLOOD_RAGE}
    },
}

SKILLS_COMMON = {
    [SKILL_LOGISTICS] = {PERK_RECRUITMENT, PERK_SPOILS_OF_WAR, PERK_WAR_PATH, PERK_PATHFINDING, PERK_SCOUTING, PERK_SNATCH},
    [SKILL_WARFARE] = {PERK_BALLISTICS, PERK_FLAMING_ARROWS, PERK_RAPIDFIRE, PERK_ANATOMY, PERK_WARFARE_LOGISTICS, PERK_HOUNDMASTERS},
    [SKILL_COMBAT] = {PERK_EMPIRICISM, PERK_COORDINATION, PERK_STUNNING_BLOW, PERK_REINFORCEMENT, PERK_AVENGING_STRIKE, PERK_BRUTALITY},
    [SKILL_TRAINING] = {PERK_TOUGHNESS, PERK_BATTLE_FRENZY, PERK_ONSLAUGHT, PERK_RUSH, PERK_EXPERTISE, PERK_STUN_TRAINING, PERK_ASSAULT_TRAINING},
    [SKILL_DESPOTISM] = {PERK_DEVOTION, PERK_BATTLE_WRATH, PERK_WAR_POLICY},
    [SKILL_GOVERNANCE] = {PERK_GEAR_UP, PERK_HEROES_LEGACY, PERK_MYTHOLOGY, PERK_ESTATES, PERK_GEOLOGY, PERK_INDUSTRY},
    [SKILL_LEADERSHIP] = {PERK_DIPLOMACY, PERK_TALETELLERS, PERK_CHARISMA, PERK_MOTIVATION, PERK_ENCOURAGE, PERK_LAST_STAND},
    [SKILL_LIGHT_MAGIC] = {PERK_AURA_OF_PROTECTION, PERK_FIRE_RESISTANCE, PERK_COUNTERSPELL, PERK_AURA_OF_ENERGY, PERK_SIPHON_GRACE, PERK_VENGEFUL_LIGHT},
    [SKILL_DARK_MAGIC] = {PERK_SPREAD_CURSE, PERK_CONSUME_CORPSE, PERK_PARIAH, PERK_SPREAD_PAIN, PERK_SPIRIT_LINK, PERK_PLAGUE_TENT},
    [SKILL_DESTRUCTIVE_MAGIC] = {PERK_BLAZE_POWER, PERK_IGNITE, PERK_SECRETS_OF_DESTRUCT, PERK_FROST_POWER, PERK_DEADLY_COLD, PERK_COLD_STEEL},
    [SKILL_NATURAL_MAGIC] = {PERK_CONJURER, PERK_ELEMENTAL_BALANCE, PERK_WARRIORS_OF_THE_MAGMA, PERK_WARRIORS_OF_THE_MOUNTAIN, PERK_WARRIORS_OF_THE_SEA, PERK_WARRIORS_OF_THE_SKY, PERK_SCORCHING_EARTH, PERK_FOG_VEIL, PERK_STORM_WIND},
    [SKILL_SHATTER_MAGIC] = {PERK_PROTECTION, PERK_SAP_MAGIC, PERK_MAGIC_FILTER, PERK_BACK_TO_THE_VOID, PERK_SPELLBREAKER, PERK_COUNTER_MAGIC, PERK_ARMOR_PROTECTION, PERK_CORRUPTION_IMMUNE},
    [SKILL_OFFENCE] = {PERK_OFFENSIVE_FORMATION, PERK_TACTICS, PERK_SWIFTNESS, PERK_ARCHERY, PERK_PRECISION, PERK_FATAL_STRIKES},
    [SKILL_DEFENSE] = {PERK_DEFENSIVE_FORMATION, PERK_HOLD_GROUND, PERK_PREPARATION, PERK_EVASION, PERK_SEAL_OF_PROTECTION, PERK_STAMINA},
    [SKILL_LEARNING] = {PERK_INTUITION, PERK_SCHOLAR, PERK_MENTORING, PERK_INTELLIGENCE, PERK_EXALTATION, PERK_MEDITATION},
    [SKILL_SORCERY] = {PERK_ARCANE_INITIATION, PERK_ARCANE_BRILLANCE, PERK_ARCANE_EXCELLENCE, PERK_MAGIC_INSIGHT, PERK_GRADUATE, PERK_OCCULTISM},
    [SKILL_VOICE] = {PERK_MIGHTY_SHOUT, PERK_VOICE_TRAINING, PERK_BLOODLUST, PERK_DOMINANT_SHOUT, PERK_LUNG_WORKOUT, PERK_INTIMIDATING_VOICE},
}


-- Skill bonuses
--
_skillbonus_id = 0 
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_OFFENCE             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_DEFENSE             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_LEARNING            = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SORCERY             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_VOICE               = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_LIGHT_MAGIC         = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_DARK_MAGIC          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_NATURAL_MAGIC       = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_DESTRUCT_MAGIC      = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_ARTIFICIER          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SPIRITISM           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_INTELLIGENCE        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_EXALTATION          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_ARCANE_EXCELLENCE   = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GRADUATE            = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_OCCULTISM           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SECRETS_OF_DESTRUCT = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_REINFORCEMENT       = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_EMPIRICISM          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_ONSLAUGHT           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_PATHFINDING         = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_WAR_PATH            = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GEAR_UP             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_HEROES_LEGACY       = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_MYTHOLOGY           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_IMBUE_ARROW         = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_BATTLE_COMMANDER    = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_FINE_RUNE           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_REFRESH_RUNE        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GREATER_RUNE        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_LORD_OF_THE_UNDEAD  = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SHEER_STRENGTH      = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_INFUSION            = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_ENLIGHTENED         = _skillbonus_id


-- log(TRACE, "Loaded skills.lua")
ROUTINES_LOADED[3] = 1
