

-- Skill type IDs
--
SKILL_NONE = 0
SKILL_LOGISTICS = 1
SKILL_SUPPORT = 2
SKILL_LEARNING = 3
PERK_MOTIVATION = 4
PERK_PRECISION = 5
SKILL_OFFENCE = 6
SKILL_DEFENSE = 7
SKILL_SORCERY = 8
SKILL_DESTRUCTIVE_MAGIC = 9
SKILL_DARK_MAGIC = 10
SKILL_LIGHT_MAGIC = 11
SKILL_NATURAL_MAGIC = 12
SKILL_COMBAT = 13
SKILL_GATING = 14
SKILL_NECROMANCY = 15
SKILL_AVENGER = 16
SKILL_ARTIFICIER = 17
SKILL_ARCANISM = 18
PERK_PATHFINDING = 19
PERK_SCOUTING = 20
SKILL_GOVERNANCE = 21
PERK_ANATOMY = 22
PERK_BALLISTICS = 23
PERK_HOUNDMASTERS = 24
PERK_INTELLIGENCE = 25
PERK_SCHOLAR = 26
PERK_INTUITION = 27
PERK_RECRUITMENT = 28
PERK_ESTATES = 29
PERK_DIPLOMACY = 30
PERK_MAGIC_RESISTANCE = 31
PERK_EXPERTISE = 32
PERK_GEOLOGY = 33
PERK_TACTICS = 34
PERK_ARCHERY = 35
PERK_BATTLE_FRENZY = 36
PERK_PROTECTION = 37
PERK_EVASION = 38
PERK_TOUGHNESS = 39
PERK_OCCULTISM = 40
PERK_MAGIC_INSIGHT = 41
PERK_ARCANE_INITIATION = 42
PERK_FROST_POWER = 43
PERK_BLAZE_POWER = 44
PERK_WARRIORS_OF_THE_SKY = 45
PERK_MASTER_OF_CURSES = 46
PERK_MASTER_OF_MIND = 47 -- unused - mass slow and confusion
PERK_MASTER_OF_PAIN = 48
PERK_MASTER_OF_BLESSINGS = 49 -- unused - mass strength and cleanse
PERK_MASTER_OF_ABJURATION = 50
PERK_MASTER_OF_WRATH = 51
PERK_MASTER_OF_QUAKES = 52 --unused - better fire traps and earthquake
PERK_CONJURER = 53
PERK_MASTER_OF_ANIMATION = 54 --unused - better fist of wrath and raise dead
PERK_RETALIATION_STRIKE = 55
PERK_PRAYER = 56
PERK_EXPERT_TRAINER = 57
PERK_CONSUME_CORPSE = 58
PERK_HELLFIRE = 59
PERK_AVENGING_STRIKE = 60
SKILL_COURAGE = 61
PERK_ETERNAL_SERVITUDE = 62
PERK_BANSHEE_HOWL = 63
PERK_RAIN_OF_ARROWS = 64
PERK_SNIPER = 65
PERK_IMBUE_ARROW = 66
PERK_MAGIC_BOND = 67
PERK_MELT_ARTIFACT = 68
PERK_MAGIC_MIRROR = 69
PERK_EMPOWERED_SPELLS = 70
PERK_MEDITATION = 71
PERK_ELEMENTAL_VISION = 72
PERK_FAMILIAR_LAND = 73
PERK_RAPIDFIRE = 74
PERK_ENCOURAGE = 75
PERK_RETRIBUTION = 76
PERK_HOLD_GROUND = 77
PERK_GUARDIAN_ANGEL = 78
PERK_STUDENT_AWARD = 79 --unused - +2 knowledge and 1000 exp
PERK_INDUSTRY = 80
PERK_INFUSION = 81
PERK_FIERY_WRATH = 82
PERK_PARIAH = 83
PERK_ELEMENTAL_BALANCE = 84
PERK_HOLY_CHARGE = 85
PERK_SWIFT_GATING = 86
PERK_EXALTATION = 87
PERK_WARRIORS_OF_THE_SEA = 88
PERK_GATE_MASTER = 89
PERK_SWARMING_GATE = 90
PERK_BRUTALITY = 91
PERK_HELLWRATH = 92
PERK_RAGE_AWAKENING = 93
PERK_SEARING_FIRES = 94
PERK_WEAKENING_STRIKE = 95
PERK_FIRE_RESISTANCE = 96
PERK_WARRIORS_OF_THE_MAGMA = 97
PERK_URGASHS_CALL = 98
PERK_SIEGE = 99
PERK_PLAGUE_TENT = 100
PERK_LORD_OF_UNDEAD = 101
PERK_HERALD_OF_DEATH = 102
PERK_DEAD_MANS_CURSE = 103
PERK_COLD_STEEL = 104
PERK_CHILLING_BONES = 105
PERK_SPELLPROOF_BONES = 106
PERK_DEADLY_COLD = 107
PERK_SPIRIT_LINK = 108
SKILL_SPIRITISM = 109
PERK_HAUNTING = 110
PERK_ABSOLUTE_FEAR = 111 --unused - banshee hown -6 morale
PERK_SILENT_TRACKER = 112
PERK_IMBUE_BALLISTA = 113
PERK_KNOW_YOUR_ENEMY = 114
PERK_BATTLE_COMMANDER = 115
PERK_FATAL_STRIKES = 116
PERK_RAGE_OF_THE_FOREST = 117
PERK_LAST_STAND = 118
PERK_WITCHCRAFT = 119
PERK_MANA_BURST = 120
PERK_SCORCHING_EARTH = 121
PERK_STORM_WIND = 122
PERK_FOG_VEIL = 123
PERK_SUPERNATURAL_LUCK = 124
PERK_MARCH_OF_THE_GOLEMS = 125
PERK_REMOTE_CONTROL = 126
PERK_ACADEMY_AWARD = 127 --unused - +2 spellpower and 1000 golds
PERK_ARTIFICIAL_GLORY = 128
PERK_SPOILS_OF_WAR = 129
PERK_FLAMING_ARROWS = 130
PERK_SEAL_OF_PROTECTION = 131 -- try spellbuff walls
PERK_COUNTERSPELL = 132
PERK_SAP_MAGIC = 133
PERK_SUPRESS_DARK = 134
PERK_SUPRESS_LIGHT = 135
PERK_BANISH = 136
PERK_OMNISCIENCE = 137
PERK_TELEPORT_ASSAULT = 138
PERK_WARRIORS_OF_THE_MOUNTAIN = 139
PERK_GRADUATE = 140
PERK_SWIFTNESS = 141
PERK_LUCKY_SPELLS = 142
PERK_POWER_OF_HASTE = 143
PERK_POWER_OF_STONE = 144
PERK_ERRATIC_MANA = 145
PERK_FORBIDDEN_POWER = 146 --unused - +2 knowledge and a damaging spell
PERK_SECRETS_OF_DESTRUCT = 147
PERK_ARCANE_BRILLANCE = 148
PERK_EXORCISM = 149 --unused - destruction spells damage doubled vs summoned
PERK_RAGE_OF_THE_ELEMENTS = 150
SKILL_RUNELORE = 151
PERK_REFRESH_RUNE = 152
PERK_GREATER_RUNE = 153
PERK_FINE_RUNE = 154
PERK_ARCANE_EXCELLENCE = 155
PERK_TECHNICAL_STAFF = 156
PERK_TAP_RUNES = 157
PERK_RUNIC_ATTUNEMENT = 158
PERK_DETERMINATION = 159
PERK_OFFENSIVE_FORMATION = 160
PERK_DEFENSIVE_FORMATION = 161
PERK_DISTRACT = 162
PERK_IGNITE = 163
PERK_TENACITY = 164
PERK_ETERNAL_LIGHT = 165
PERK_RUNIC_SHIELD = 166
PERK_BULWARK_RUNE = 167
PERK_SNATCH = 168
PERK_MENTORING = 169
PERK_EMPATHY = 170
PERK_PREPARATION = 171
SKILL_BLOOD_RAGE = 172
PERK_MIGHT_OVER_MAGIC = 173
PERK_MEMORY_OF_OUR_BLOOD = 174
PERK_COORDINATION = 175
PERK_ORCISH_FURY = 176
PERK_WAR_PATH = 177
PERK_BATTLE_ELATION = 178
PERK_PAIN_KILLER = 179
PERK_STUNNING_BLOW = 180
PERK_DEFEND_US_ALL = 181
PERK_GOBLIN_SUPPORT = 182
SKILL_BARBARIAN_LEARNING = 183 --unused
PERK_BLOODFIRE = 184
SKILL_TRAINING = 185
PERK_SHEER_STRENGTH = 186
SKILL_VOICE = 187
PERK_VOICE_TRAINING = 188
PERK_MIGHTY_SHOUT = 189
PERK_BLOODLUST = 190
PERK_LEADERSHIP_TODO1 = 191
PERK_CHARISMA = 192
PERK_WARM_UP = 193
PERK_DETAIN_DESTRUCTIVE = 194 -- try rune of magic control
SKILL_SHATTER_DARK = 195 -- CAN BE USED
PERK_CORRUPT_DARK = 196 -- CAN BE USED
PERK_WEAKEN_DARK = 197 -- CAN BE USED
PERK_DETAIN_DARK = 198 -- CAN BE USED
SKILL_SHATTER_MAGIC = 199
PERK_GEAR_UP = 200
PERK_HEROES_LEGACY = 201
PERK_MYTHOLOGY = 202
SKILL_INNATES = 203
PERK_CORRUPT_NATURAL = 204 -- CAN BE USED
PERK_WEAKEN_NATURAL = 205 -- CAN BE USED
PERK_DETAIN_NATURAL = 206 -- CAN BE USED
PERK_BACK_TO_THE_VOID = 207
PERK_BARBARIAN_ANCIENT_SMITHY = 208 --unused
PERK_BARBARIAN_WEAKENING_STRIKE = 209 --unused
PERK_BARBARIAN_SOIL_BURN = 210 --unused
PERK_BARBARIAN_FOG_VEIL = 211 --unused
SKILL_LEADERSHIP = 212
PERK_BARBARIAN_MYSTICISM = 213 --unused
PERK_BARBARIAN_ELITE_CASTERS = 214 --unused
PERK_BARBARIAN_STORM_WIND = 215 --unused
PERK_BARBARIAN_FIRE_PROTECTION = 216 -- CAN BE USED - Morale debuff attacks
PERK_BARBARIAN_SUN_FIRE = 217 --unused
PERK_BARBARIAN_DISTRACT = 218 --unused
PERK_ULTIMATE = 219
PERK_BARBARIAN_MENTORING = 220 --unused

-- Skill bonuses ID
--
_skillbonus_id = 0 
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_OFFENCE             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_DEFENSE             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_LEARNING            = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SORCERY             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_VOICE               = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_COMBAT              = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_COURAGE             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_AVENGER             = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SPIRITISM           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_PRECISION           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_INTELLIGENCE        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_EXALTATION          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_ARCANE_EXCELLENCE   = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GRADUATE            = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_OCCULTISM           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SECRETS_OF_DESTRUCT = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_MOTIVATION          = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_BATTLE_COMMANDER    = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_FINE_RUNE           = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_REFRESH_RUNE        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_GREATER_RUNE        = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_LORD_OF_THE_UNDEAD  = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_DEFEND_US_ALL       = _skillbonus_id
_skillbonus_id = _skillbonus_id + 1; SKILLBONUS_SHEER_STRENGTH      = _skillbonus_id


-- print("Loaded skills data script")
ROUTINES_LOADED[15] = 1
