
name: Package data

on:
  push:
    paths: 
      - 'game_data/data/**'

jobs:
  package-data-folder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Pack data
        uses: ./.github/workflows/actions/package
        with:
          folder: data
